import { Platform, StyleSheet } from 'react-native';
import type { AppTheme } from '../../types/theme';

export const SIDEBAR_WIDTH = 296;
export const DESKTOP_BREAKPOINT = 1024;

export type ShellPalette = {
  brand: string;
  navIconDefault: string;
  navIconActive: string;
  surfaceIcon: string;
};

function getTokens(theme: AppTheme) {
  if (theme === 'dark') {
    return {
      shellBackground: '#101214',
      backdropOrbPrimary: 'rgba(171, 30, 36, 0.16)',
      backdropOrbSecondary: 'rgba(197, 118, 88, 0.12)',
      border: 'rgba(255, 255, 255, 0.08)',
      card: 'rgba(24, 27, 31, 0.94)',
      panel: '#1a1e23',
      panelSoft: '#15181c',
      text: '#f3e7e4',
      muted: '#b89f9b',
      brand: '#d45a60',
      sidebarBorder: 'rgba(255, 255, 255, 0.08)',
      sidebarBackground: '#15181c',
      sidebarLabel: '#d8b9b3',
      navDefaultText: '#f1e3e0',
      navActiveText: '#ffffff',
      navIconDefault: '#f3e7e4',
      navIconActive: '#ffffff',
      navItemBackground: 'rgba(255, 255, 255, 0.03)',
      navItemBorder: 'rgba(255, 255, 255, 0.06)',
      navItemActiveBackground: 'rgba(212, 90, 96, 0.22)',
      navItemActiveBorder: 'rgba(212, 90, 96, 0.4)',
      navIconWrapBackground: 'rgba(255, 255, 255, 0.07)',
      navIconWrapActiveBackground: 'rgba(212, 90, 96, 0.26)',
      chipBackground: 'rgba(255, 255, 255, 0.05)',
      chipBorder: 'rgba(255, 255, 255, 0.08)',
      chipActiveBackground: 'rgba(212, 90, 96, 0.18)',
      chipActiveBorder: 'rgba(212, 90, 96, 0.4)',
      chipText: '#f3e7e4',
      chipActiveText: '#ffffff',
      brandBadgeBackground: 'rgba(255, 255, 255, 0.08)',
      brandBadgeText: '#f9e5e1',
      brandBlockBackground: 'rgba(255, 255, 255, 0.03)',
      brandBlockBorder: 'rgba(255, 255, 255, 0.08)',
      brandValuesText: '#ffffff',
      userCardBackground: '#1b1f24',
      userCardBorder: 'rgba(255, 255, 255, 0.08)',
      userAvatarBackground: '#2b2220',
      userDetailBackground: 'rgba(255, 255, 255, 0.03)',
      userDetailBorder: 'rgba(255, 255, 255, 0.08)',
      userDetailIconBackground: 'rgba(212, 90, 96, 0.18)',
      logoutBackground: '#22191b',
      logoutBorder: 'rgba(212, 90, 96, 0.28)',
      logoutText: '#ffffff',
      mobileBackdrop: 'rgba(6, 8, 10, 0.54)',
      shadowSurface: '#ffffff',
    };
  }

  return {
    shellBackground: '#f6efe8',
    backdropOrbPrimary: 'rgba(171, 30, 36, 0.08)',
    backdropOrbSecondary: 'rgba(190, 111, 77, 0.08)',
    border: 'rgba(142, 34, 40, 0.18)',
    card: 'rgba(255, 251, 247, 0.94)',
    panel: '#ffffff',
    panelSoft: '#fff8f5',
    text: '#5f1c21',
    muted: '#8d5a5f',
    brand: '#ab1e24',
    sidebarBorder: '#97161c',
    sidebarBackground: '#ab1e24',
    sidebarLabel: '#f6d9d4',
    navDefaultText: '#fff7f5',
    navActiveText: '#ffffff',
    navIconDefault: '#ffffff',
    navIconActive: '#ab1e24',
    navItemBackground: 'rgba(255, 255, 255, 0.04)',
    navItemBorder: 'rgba(255, 255, 255, 0.08)',
    navItemActiveBackground: 'rgba(255, 255, 255, 0.12)',
    navItemActiveBorder: 'rgba(255, 255, 255, 0.16)',
    navIconWrapBackground: 'rgba(255, 255, 255, 0.12)',
    navIconWrapActiveBackground: '#ffffff',
    chipBackground: 'rgba(255, 255, 255, 0.06)',
    chipBorder: 'rgba(255, 255, 255, 0.12)',
    chipActiveBackground: '#fff5f3',
    chipActiveBorder: 'rgba(255, 255, 255, 0.16)',
    chipText: '#fff7f5',
    chipActiveText: '#ab1e24',
    brandBadgeBackground: '#fff5f3',
    brandBadgeText: '#ab1e24',
    brandBlockBackground: 'rgba(255, 248, 245, 0.12)',
    brandBlockBorder: 'rgba(255, 255, 255, 0.18)',
    brandValuesText: '#ffffff',
    userCardBackground: '#ffffff',
    userCardBorder: 'rgba(171, 30, 36, 0.18)',
    userAvatarBackground: '#f7e8e0',
    userDetailBackground: '#fff8f5',
    userDetailBorder: 'rgba(171, 30, 36, 0.14)',
    userDetailIconBackground: '#fff1ef',
    logoutBackground: '#fff5f3',
    logoutBorder: 'rgba(171, 30, 36, 0.16)',
    logoutText: '#ab1e24',
    mobileBackdrop: 'rgba(61, 26, 29, 0.22)',
    shadowSurface: '#ffffff',
  };
}

export function getShellPalette(theme: AppTheme): ShellPalette {
  const tokens = getTokens(theme);

  return {
    brand: tokens.brand,
    navIconDefault: tokens.navIconDefault,
    navIconActive: tokens.navIconActive,
    surfaceIcon: tokens.brand,
  };
}

export function createStyles(theme: AppTheme) {
  const tokens = getTokens(theme);

  return StyleSheet.create({
    shellRoot: {
      flex: 1,
      position: 'relative',
      overflow: 'hidden',
      backgroundColor: tokens.shellBackground,
    },
    shellBackdrop: {
      ...StyleSheet.absoluteFillObject,
    },
    backdropOrbPrimary: {
      position: 'absolute',
      top: -96,
      left: -72,
      width: 240,
      height: 240,
      borderRadius: 999,
      backgroundColor: tokens.backdropOrbPrimary,
    },
    backdropOrbSecondary: {
      position: 'absolute',
      right: -64,
      bottom: 80,
      width: 260,
      height: 260,
      borderRadius: 999,
      backgroundColor: tokens.backdropOrbSecondary,
    },
    shellLayout: {
      flex: 1,
      flexDirection: 'row',
    },
    sidebarRail: {
      width: SIDEBAR_WIDTH,
      padding: 20,
      paddingRight: 12,
    },
    sidebarPanel: {
      flex: 1,
      borderRadius: 28,
      borderWidth: 1,
      borderColor: tokens.sidebarBorder,
      backgroundColor: tokens.sidebarBackground,
      overflow: 'hidden',
    },
    sidebarPanelContent: {
      flexGrow: 1,
      padding: 18,
      gap: 18,
    },
    brandBlock: {
      borderRadius: 22,
      borderWidth: 1,
      borderColor: tokens.brandBlockBorder,
      backgroundColor: tokens.brandBlockBackground,
      padding: 16,
      gap: 10,
    },
    brandBadge: {
      alignSelf: 'flex-start',
      borderRadius: 999,
      backgroundColor: tokens.brandBadgeBackground,
      paddingHorizontal: 10,
      paddingVertical: 5,
    },
    brandBadgeText: {
      color: tokens.brandBadgeText,
      fontFamily: 'Manrope_700Bold',
      fontSize: 11,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    brandStatusDot: {
      width: 8,
      height: 8,
      borderRadius: 999,
      backgroundColor: tokens.brand,
    },
    brandValuesStack: {
      gap: 4,
    },
    brandValuesText: {
      color: tokens.brandValuesText,
      fontFamily: 'Manrope_700Bold',
      fontSize: 12,
      lineHeight: 18,
    },
    sidebarUserCard: {
      borderRadius: 24,
      borderWidth: 1,
      borderColor: tokens.userCardBorder,
      backgroundColor: tokens.userCardBackground,
      padding: 16,
      gap: 12,
    },
    sidebarUserTopRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 14,
    },
    sidebarUserAvatar: {
      width: 54,
      height: 54,
      borderRadius: 18,
      backgroundColor: tokens.userAvatarBackground,
      alignItems: 'center',
      justifyContent: 'center',
      overflow: 'hidden',
    },
    sidebarUserAvatarImage: {
      width: '100%',
      height: '100%',
    },
    sidebarUserAvatarText: {
      color: tokens.brand,
      fontFamily: 'Manrope_700Bold',
      fontSize: 22,
    },
    sidebarUserTextWrap: {
      flex: 1,
      gap: 4,
    },
    sidebarUserName: {
      color: tokens.text,
      fontFamily: 'Manrope_700Bold',
      fontSize: 18,
    },
    sidebarUserRole: {
      color: tokens.muted,
      fontFamily: 'Manrope_700Bold',
      fontSize: 12,
    },
    sidebarUserDetailRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 10,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: tokens.userDetailBorder,
      backgroundColor: tokens.userDetailBackground,
      paddingHorizontal: 12,
      paddingVertical: 10,
    },
    sidebarUserDetailIcon: {
      width: 22,
      height: 22,
      borderRadius: 999,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: tokens.userDetailIconBackground,
      marginTop: 1,
    },
    sidebarUserDetailTextWrap: {
      flex: 1,
      minWidth: 0,
    },
    sidebarUserDetailText: {
      color: tokens.muted,
      fontFamily: 'Manrope_400Regular',
      fontSize: 12,
      lineHeight: 17,
      flexShrink: 1,
    },
    sidebarLabel: {
      color: tokens.sidebarLabel,
      fontFamily: 'Manrope_700Bold',
      fontSize: 11,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    navSection: {
      gap: 10,
    },
    navList: {
      gap: 8,
    },
    navItem: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: tokens.navItemBorder,
      backgroundColor: tokens.navItemBackground,
      paddingHorizontal: 12,
      paddingVertical: 11,
    },
    navItemActive: {
      borderColor: tokens.navItemActiveBorder,
      backgroundColor: tokens.navItemActiveBackground,
    },
    navItemIconWrap: {
      width: 34,
      height: 34,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: tokens.navIconWrapBackground,
    },
    navItemIconWrapActive: {
      backgroundColor: tokens.navIconWrapActiveBackground,
    },
    navItemText: {
      flex: 1,
      color: tokens.navDefaultText,
      fontFamily: 'Manrope_700Bold',
      fontSize: 14,
    },
    navItemTextActive: {
      color: tokens.navActiveText,
    },
    navGroup: {
      gap: 8,
    },
    navSubList: {
      gap: 8,
      paddingLeft: 12,
    },
    navSubItem: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: tokens.navItemBorder,
      backgroundColor: tokens.navItemBackground,
      paddingHorizontal: 12,
      paddingVertical: 9,
    },
    navSubItemActive: {
      borderColor: tokens.navItemActiveBorder,
      backgroundColor: tokens.navItemActiveBackground,
    },
    navSubIconWrap: {
      width: 28,
      height: 28,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: tokens.navIconWrapBackground,
    },
    navSubIconWrapActive: {
      backgroundColor: tokens.navIconWrapActiveBackground,
    },
    navSubItemText: {
      flex: 1,
      color: tokens.sidebarLabel,
      fontFamily: 'Manrope_700Bold',
      fontSize: 12,
    },
    navSubItemTextActive: {
      color: tokens.navActiveText,
    },
    sidebarFooter: {
      marginTop: 'auto',
      gap: 14,
    },
    themeGroup: {
      gap: 8,
    },
    themeRow: {
      flexDirection: 'row',
      gap: 8,
    },
    themeChip: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: tokens.chipBorder,
      backgroundColor: tokens.chipBackground,
      paddingVertical: 10,
      paddingHorizontal: 8,
    },
    themeChipActive: {
      borderColor: tokens.chipActiveBorder,
      backgroundColor: tokens.chipActiveBackground,
    },
    themeChipText: {
      color: tokens.chipText,
      fontFamily: 'Manrope_700Bold',
      fontSize: 12,
    },
    themeChipTextActive: {
      color: tokens.chipActiveText,
    },
    languageGroup: {
      gap: 8,
    },
    languageRow: {
      flexDirection: 'row',
      gap: 8,
    },
    languageChip: {
      flex: 1,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: tokens.chipBorder,
      backgroundColor: tokens.chipBackground,
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 10,
    },
    languageChipActive: {
      borderColor: tokens.chipActiveBorder,
      backgroundColor: tokens.chipActiveBackground,
    },
    languageChipText: {
      color: tokens.chipText,
      fontFamily: 'Manrope_700Bold',
      fontSize: 12,
    },
    languageChipTextActive: {
      color: tokens.chipActiveText,
    },
    logoutButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: tokens.logoutBorder,
      backgroundColor: tokens.logoutBackground,
      paddingVertical: 12,
    },
    logoutSection: {
      marginTop: 6,
      paddingTop: 12,
      borderTopWidth: 1,
      borderTopColor: tokens.chipBorder,
    },
    logoutButtonText: {
      color: tokens.logoutText,
      fontFamily: 'Manrope_700Bold',
      fontSize: 14,
    },
    mainColumn: {
      flex: 1,
      paddingHorizontal: 16,
      paddingVertical: 18,
      gap: 16,
      // On very wide web screens (> 1600px), prevent content from stretching too far.
      // Since the sidebar anchors content from the left, we only cap at maxWidth.
      ...Platform.select({
        web: { maxWidth: 1600 } as never,
        default: {},
      }),
    },
    topBar: {
      borderRadius: 28,
      borderWidth: 1,
      borderColor: tokens.border,
      backgroundColor: tokens.card,
      paddingHorizontal: 22,
      paddingVertical: 18,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 16,
    },
    topBarTextWrap: {
      flex: 1,
      gap: 4,
    },
    topBarEyebrow: {
      color: tokens.muted,
      fontFamily: 'Manrope_700Bold',
      fontSize: 12,
    },
    topBarTitle: {
      color: tokens.text,
      fontFamily: 'Manrope_700Bold',
      fontSize: 26,
      lineHeight: 32,
    },
    topBarSubtitle: {
      color: tokens.muted,
      fontFamily: 'Manrope_400Regular',
      fontSize: 13,
      lineHeight: 18,
    },
    topBarMetaRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    topBarInfoCard: {
      borderRadius: 18,
      borderWidth: 1,
      borderColor: tokens.border,
      backgroundColor: tokens.panel,
      paddingHorizontal: 12,
      paddingVertical: 9,
      gap: 4,
      minWidth: 132,
    },
    topBarInfoLabel: {
      color: tokens.muted,
      fontFamily: 'Manrope_700Bold',
      fontSize: 11,
    },
    topBarInfoStatusRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    topBarInfoValue: {
      color: tokens.text,
      fontFamily: 'Manrope_700Bold',
      fontSize: 13,
    },
    topBarInfoMeta: {
      color: tokens.muted,
      fontFamily: 'Manrope_400Regular',
      fontSize: 11,
    },
    statusPill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: tokens.border,
      backgroundColor: tokens.panel,
      paddingHorizontal: 12,
      paddingVertical: 9,
    },
    statusPillText: {
      color: tokens.text,
      fontFamily: 'Manrope_700Bold',
      fontSize: 12,
    },
    quickUserPill: {
      borderRadius: 18,
      borderWidth: 1,
      borderColor: tokens.border,
      backgroundColor: tokens.panel,
      paddingHorizontal: 12,
      paddingVertical: 9,
      gap: 2,
      minWidth: 170,
    },
    quickUserName: {
      color: tokens.text,
      fontFamily: 'Manrope_700Bold',
      fontSize: 12,
    },
    quickUserMeta: {
      color: tokens.muted,
      fontFamily: 'Manrope_400Regular',
      fontSize: 11,
    },
    mobileMenuButton: {
      width: 44,
      height: 44,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: tokens.border,
      backgroundColor: tokens.panel,
      alignItems: 'center',
      justifyContent: 'center',
    },
    contentViewport: {
      flex: 1,
      minHeight: 0,
      position: 'relative',
    },
    contentDarkScrim: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: 'rgba(7, 10, 13, 0.18)',
      zIndex: 2,
    },
    mobileBackdrop: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: tokens.mobileBackdrop,
      zIndex: 4,
    },
    mobileDrawerWrap: {
      position: 'absolute',
      top: 18,
      bottom: 18,
      left: 16,
      width: SIDEBAR_WIDTH,
      zIndex: 5,
      elevation: 8,
    },
  });
}
