import { StyleSheet } from 'react-native';

const BORDER = 'rgba(171, 30, 36, 0.12)';
const SOFT_BORDER = 'rgba(171, 30, 36, 0.08)';
const CARD = '#fffdfb';
const PANEL = '#ffffff';
const PANEL_SOFT = '#fff7f4';
const BRAND = '#ab1e24';
const BRAND_SOFT = '#fff1ee';
const TEXT = '#5f1c21';
const MUTED = '#8d5a5f';

export const styles = StyleSheet.create({
  pageRoot: {
    flex: 1,
  },
  pageScroll: {
    flex: 1,
  },
  pageContent: {
    gap: 18,
    paddingBottom: 24,
  },
  heroCard: {
    borderRadius: 28,
    borderWidth: 1,
    borderColor: BORDER,
    backgroundColor: CARD,
    padding: 20,
    gap: 16,
  },
  heroHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 14,
    flexWrap: 'wrap',
  },
  heroCopy: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  title: {
    color: TEXT,
    fontFamily: 'Manrope_700Bold',
    fontSize: 28,
    lineHeight: 34,
  },
  subtitle: {
    color: MUTED,
    fontFamily: 'Manrope_400Regular',
    fontSize: 13,
    lineHeight: 19,
  },
  heroHeaderActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flexWrap: 'wrap',
  },
  heroBadge: {
    maxWidth: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: SOFT_BORDER,
    backgroundColor: BRAND_SOFT,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  heroBadgeText: {
    color: BRAND,
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
    maxWidth: 220,
  },
  heroActionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: SOFT_BORDER,
    backgroundColor: PANEL,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  heroActionButtonText: {
    color: BRAND,
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
  },
  heroMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  metaPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: SOFT_BORDER,
    backgroundColor: PANEL_SOFT,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  metaPillText: {
    color: BRAND,
    fontFamily: 'Manrope_700Bold',
    fontSize: 11,
  },
  heroStatsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  heroStatCard: {
    minWidth: 150,
    flex: 1,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: SOFT_BORDER,
    backgroundColor: PANEL,
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 4,
  },
  heroStatLabel: {
    color: MUTED,
    fontFamily: 'Manrope_700Bold',
    fontSize: 11,
  },
  heroStatValue: {
    color: TEXT,
    fontFamily: 'Manrope_700Bold',
    fontSize: 22,
    lineHeight: 28,
  },
  toolbarCard: {
    borderRadius: 26,
    borderWidth: 1,
    borderColor: BORDER,
    backgroundColor: CARD,
    padding: 18,
    gap: 16,
  },
  toolbarGrid: {
    gap: 16,
  },
  toolbarGridWide: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    flexWrap: 'wrap',
  },
  toolSection: {
    gap: 10,
  },
  searchSection: {
    flex: 1,
    minWidth: 260,
  },
  toolSectionWide: {
    flex: 1,
    minWidth: 260,
  },
  toolSectionTitle: {
    color: MUTED,
    fontFamily: 'Manrope_700Bold',
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  chipRail: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingRight: 10,
  },
  supplierChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: SOFT_BORDER,
    backgroundColor: PANEL,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  supplierChipActive: {
    borderColor: BRAND,
    backgroundColor: BRAND_SOFT,
  },
  supplierChipText: {
    color: TEXT,
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
    maxWidth: 180,
  },
  supplierChipTextActive: {
    color: BRAND,
  },
  supplierChipCount: {
    minWidth: 28,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 999,
    borderWidth: 1,
    borderColor: SOFT_BORDER,
    backgroundColor: PANEL_SOFT,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  supplierChipCountActive: {
    borderColor: 'rgba(171, 30, 36, 0.18)',
    backgroundColor: '#ffffff',
  },
  supplierChipCountText: {
    color: MUTED,
    fontFamily: 'Manrope_700Bold',
    fontSize: 11,
  },
  supplierChipCountTextActive: {
    color: BRAND,
  },
  searchShell: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: SOFT_BORDER,
    backgroundColor: PANEL,
    paddingHorizontal: 14,
  },
  searchInput: {
    flex: 1,
    minWidth: 0,
    color: TEXT,
    fontFamily: 'Manrope_400Regular',
    fontSize: 14,
    paddingVertical: 13,
  },
  filterWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  filterChip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: SOFT_BORDER,
    backgroundColor: PANEL,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  filterChipActive: {
    borderColor: BRAND,
    backgroundColor: BRAND_SOFT,
  },
  filterChipText: {
    color: TEXT,
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
  },
  filterChipTextActive: {
    color: BRAND,
  },
  statusCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: SOFT_BORDER,
    backgroundColor: CARD,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  statusText: {
    color: TEXT,
    fontFamily: 'Manrope_700Bold',
    fontSize: 13,
  },
  summaryCard: {
    borderRadius: 26,
    borderWidth: 1,
    borderColor: BORDER,
    backgroundColor: CARD,
    padding: 18,
    gap: 16,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  sectionHeaderCopy: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  sectionEyebrow: {
    color: MUTED,
    fontFamily: 'Manrope_700Bold',
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  sectionTitle: {
    color: TEXT,
    fontFamily: 'Manrope_700Bold',
    fontSize: 20,
    lineHeight: 26,
  },
  sectionSubtitle: {
    color: MUTED,
    fontFamily: 'Manrope_400Regular',
    fontSize: 12,
    lineHeight: 18,
  },
  sectionCountPill: {
    minWidth: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 999,
    borderWidth: 1,
    borderColor: SOFT_BORDER,
    backgroundColor: BRAND_SOFT,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  sectionCountText: {
    color: BRAND,
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
  },
  kpiGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  kpiCard: {
    minWidth: 180,
    flex: 1,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: SOFT_BORDER,
    backgroundColor: PANEL,
    padding: 14,
    gap: 6,
  },
  kpiLabel: {
    color: MUTED,
    fontFamily: 'Manrope_700Bold',
    fontSize: 11,
  },
  kpiValue: {
    color: TEXT,
    fontFamily: 'Manrope_700Bold',
    fontSize: 21,
    lineHeight: 26,
  },
  kpiMetaRow: {
    gap: 3,
  },
  kpiMetaText: {
    color: MUTED,
    fontFamily: 'Manrope_400Regular',
    fontSize: 11,
  },
  analyticsGrid: {
    gap: 18,
  },
  analyticsGridWide: {
    flexDirection: 'row',
    alignItems: 'stretch',
    flexWrap: 'wrap',
  },
  infoCard: {
    flex: 1,
    minWidth: 260,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: BORDER,
    backgroundColor: CARD,
    padding: 18,
    gap: 12,
  },
  infoCardTitle: {
    color: TEXT,
    fontFamily: 'Manrope_700Bold',
    fontSize: 16,
    lineHeight: 22,
  },
  comparisonBlock: {
    gap: 6,
  },
  comparisonRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  comparisonLabel: {
    color: MUTED,
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
  },
  comparisonValue: {
    color: TEXT,
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
  },
  comparisonTrack: {
    height: 10,
    borderRadius: 999,
    backgroundColor: '#f3e3e1',
    overflow: 'hidden',
  },
  comparisonBarCurrent: {
    height: '100%',
    minWidth: 8,
    backgroundColor: BRAND,
  },
  comparisonBarPrevious: {
    height: '100%',
    minWidth: 8,
    backgroundColor: '#d8a4a7',
  },
  comparisonDelta: {
    color: BRAND,
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
  },
  insightRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  insightText: {
    flex: 1,
    minWidth: 0,
    color: TEXT,
    fontFamily: 'Manrope_400Regular',
    fontSize: 13,
    lineHeight: 19,
  },
  trendRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: SOFT_BORDER,
    backgroundColor: PANEL,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  trendMonth: {
    color: TEXT,
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
  },
  trendValues: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  trendMetric: {
    color: MUTED,
    fontFamily: 'Manrope_700Bold',
    fontSize: 11,
  },
  historyCard: {
    borderRadius: 26,
    borderWidth: 1,
    borderColor: BORDER,
    backgroundColor: CARD,
    padding: 18,
    gap: 16,
  },
  emptyState: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: SOFT_BORDER,
    backgroundColor: PANEL,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  emptyStateText: {
    color: TEXT,
    fontFamily: 'Manrope_700Bold',
    fontSize: 13,
  },
  listBlock: {
    gap: 12,
  },
  dateSection: {
    borderRadius: 22,
    borderWidth: 1,
    borderColor: SOFT_BORDER,
    backgroundColor: PANEL,
    padding: 14,
    gap: 14,
  },
  dateSectionOpen: {
    borderColor: BORDER,
    backgroundColor: PANEL_SOFT,
  },
  dateHeaderButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  dateHeaderMain: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  dateIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: SOFT_BORDER,
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  dateInfo: {
    flex: 1,
    minWidth: 0,
    gap: 8,
  },
  dateTitle: {
    color: TEXT,
    fontFamily: 'Manrope_700Bold',
    fontSize: 15,
  },
  dateMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  dateMetaPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: SOFT_BORDER,
    backgroundColor: '#ffffff',
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  dateMetaText: {
    color: MUTED,
    fontFamily: 'Manrope_700Bold',
    fontSize: 11,
  },
  ordersGrid: {
    gap: 12,
  },
  orderCard: {
    borderRadius: 20,
    borderWidth: 1,
    borderColor: SOFT_BORDER,
    backgroundColor: '#ffffff',
    padding: 14,
    gap: 14,
  },
  orderCardHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
    flexWrap: 'wrap',
  },
  orderCardCopy: {
    flex: 1,
    minWidth: 220,
    gap: 4,
  },
  orderNumber: {
    color: TEXT,
    fontFamily: 'Manrope_700Bold',
    fontSize: 15,
  },
  orderAddress: {
    color: MUTED,
    fontFamily: 'Manrope_400Regular',
    fontSize: 12,
    lineHeight: 18,
  },
  orderAmountPill: {
    minWidth: 140,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: SOFT_BORDER,
    backgroundColor: BRAND_SOFT,
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 3,
  },
  orderAmountLabel: {
    color: MUTED,
    fontFamily: 'Manrope_700Bold',
    fontSize: 10,
  },
  orderAmountValue: {
    color: BRAND,
    fontFamily: 'Manrope_700Bold',
    fontSize: 16,
  },
  orderMetaGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  orderMetaItem: {
    flex: 1,
    minWidth: 220,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: SOFT_BORDER,
    backgroundColor: PANEL_SOFT,
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 4,
  },
  orderMetaItemSmall: {
    minWidth: 140,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: SOFT_BORDER,
    backgroundColor: PANEL_SOFT,
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 4,
  },
  orderMetaLabel: {
    color: MUTED,
    fontFamily: 'Manrope_700Bold',
    fontSize: 10,
  },
  orderMetaValue: {
    color: TEXT,
    fontFamily: 'Manrope_400Regular',
    fontSize: 12,
    lineHeight: 18,
  },
  orderActionsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  primaryButton: {
    flex: 1,
    minWidth: 200,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderRadius: 16,
    backgroundColor: BRAND,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  primaryButtonText: {
    color: '#ffffff',
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
  },
  secondaryButton: {
    flex: 1,
    minWidth: 200,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: SOFT_BORDER,
    backgroundColor: '#ffffff',
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  secondaryButtonText: {
    color: BRAND,
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
  },
  disabledButton: {
    opacity: 0.5,
  },
});
