import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  page: {
    flex: 1,
    backgroundColor: '#fff3f4',
  },
  appFrame: {
    flex: 1,
  },
  safeArea: {
    flex: 1,
  },
  keyboardAreaContent: {
    flex: 1,
    zIndex: 1,
  },
  content: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingHorizontal: 20,
    paddingVertical: 28,
    gap: 18,
  },
  contentWithHeader: {
    paddingTop: 12,
  },
  loaderPage: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff3f4',
  },
  badge: {
    alignSelf: 'center',
    backgroundColor: '#ab1e24',
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  badgeText: {
    color: '#fff4f4',
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
    letterSpacing: 0.4,
  },
  headerBar: {
    height: 72,
    borderRadius: 18,
    marginHorizontal: 12,
    marginTop: 8,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: '#e4afb0',
    backgroundColor: 'rgba(255,245,246,0.95)',
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 3,
  },
  menuTrigger: {
    width: 42,
    height: 42,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ab1e24',
  },
  menuTriggerText: {
    color: '#f7fffd',
    fontFamily: 'Manrope_700Bold',
    fontSize: 18,
  },
  headerTitleWrap: {
    flex: 1,
    paddingHorizontal: 12,
  },
  headerTitle: {
    color: '#6f1519',
    fontFamily: 'Manrope_700Bold',
    fontSize: 16,
  },
  headerSubtitle: {
    color: '#8b3a3f',
    fontFamily: 'Manrope_400Regular',
    fontSize: 12,
    marginTop: 2,
  },
  headerDot: {
    width: 10,
    height: 10,
    borderRadius: 999,
    backgroundColor: '#ab1e24',
  },
  drawerBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(80, 20, 24, 0.3)',
    zIndex: 2,
  },
  drawerPanel: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: 280,
    backgroundColor: '#7f1b21',
    paddingTop: 110,
    paddingHorizontal: 16,
    gap: 10,
    zIndex: 4,
  },
  drawerTitle: {
    color: '#ffe6e7',
    fontFamily: 'Manrope_700Bold',
    fontSize: 15,
    marginBottom: 8,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  drawerItem: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#cf7f83',
    backgroundColor: '#962028',
    paddingVertical: 12,
    paddingHorizontal: 12,
  },
  drawerItemActive: {
    backgroundColor: '#ab1e24',
    borderColor: '#e4afb0',
  },
  drawerItemText: {
    color: '#ebfffb',
    fontFamily: 'Manrope_700Bold',
    fontSize: 14,
  },
  languageSection: {
    marginTop: 14,
    borderTopWidth: 1,
    borderTopColor: '#cf7f83',
    paddingTop: 14,
    gap: 8,
  },
  languageTitle: {
    color: '#ffd9db',
    fontFamily: 'Manrope_700Bold',
    fontSize: 13,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  languageRow: {
    flexDirection: 'row',
    gap: 8,
  },
  languageChip: {
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#cf7f83',
    backgroundColor: '#962028',
  },
  languageChipActive: {
    backgroundColor: '#ab1e24',
    borderColor: '#e4afb0',
  },
  languageChipText: {
    color: '#ebfffb',
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
  },
  listBlock: {
    gap: 8,
    marginTop: 4,
  },
  listItem: {
    color: '#6d3034',
    fontFamily: 'Manrope_400Regular',
    fontSize: 14,
    lineHeight: 20,
  },
  card: {
    backgroundColor: 'rgba(255,255,255,0.92)',
    borderRadius: 22,
    padding: 18,
    borderWidth: 1,
    borderColor: '#e8c3c4',
    gap: 12,
  },
  stackCardWrap: {
    gap: 14,
  },
  uploadCard: {
    backgroundColor: 'rgba(255,255,255,0.92)',
    borderRadius: 22,
    padding: 18,
    borderWidth: 1,
    borderColor: '#e8c3c4',
    gap: 10,
  },
  uploadTitle: {
    color: '#7a181d',
    fontFamily: 'Manrope_700Bold',
    fontSize: 20,
    lineHeight: 26,
  },
  uploadSubtitle: {
    color: '#8b4a4f',
    fontFamily: 'Manrope_400Regular',
    fontSize: 13,
    lineHeight: 18,
  },
  uploadFieldTitle: {
    color: '#7f1b21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  uploadChipWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  uploadChip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#dfb0b2',
    backgroundColor: '#f9ebec',
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  uploadChipActive: {
    backgroundColor: '#ab1e24',
    borderColor: '#ab1e24',
  },
  uploadChipText: {
    color: '#7f1b21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
  },
  uploadChipTextActive: {
    color: '#ffffff',
  },
  uploadResultBox: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e0b7b9',
    backgroundColor: '#fbefef',
    padding: 10,
    gap: 6,
  },
  uploadResultText: {
    color: '#7b2328',
    fontFamily: 'Manrope_700Bold',
    fontSize: 13,
  },
  uploadResultLink: {
    color: '#ab1e24',
    fontFamily: 'Manrope_400Regular',
    fontSize: 12,
  },
  uploadResultMeta: {
    color: '#91555a',
    fontFamily: 'Manrope_400Regular',
    fontSize: 12,
  },
  title: {
    color: '#7a181d',
    fontFamily: 'Manrope_700Bold',
    fontSize: 24,
    lineHeight: 30,
  },
  subtitle: {
    color: '#8d5458',
    fontFamily: 'Manrope_400Regular',
    fontSize: 13,
  },
  sectionTitle: {
    color: '#7f1b21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 18,
    lineHeight: 24,
    marginTop: 2,
  },
  trainingTabRow: {
    flexDirection: 'row',
    gap: 8,
    paddingVertical: 4,
  },
  trainingTab: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#dfb0b2',
    backgroundColor: '#f9ebec',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  trainingTabActive: {
    backgroundColor: '#ab1e24',
    borderColor: '#ab1e24',
  },
  trainingTabText: {
    color: '#7f1b21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 13,
  },
  trainingTabTextActive: {
    color: '#ffffff',
  },
  docBlock: {
    marginTop: 8,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#e4c3c5',
    backgroundColor: '#fff7f7',
    padding: 12,
    gap: 8,
  },
  docBlockTitle: {
    color: '#7f1b21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 14,
  },
  docEmpty: {
    color: '#a06a6f',
    fontFamily: 'Manrope_400Regular',
    fontSize: 13,
  },
  docItem: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#edd4d5',
    backgroundColor: '#ffffff',
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 4,
  },
  docItemTitle: {
    color: '#7a2328',
    fontFamily: 'Manrope_700Bold',
    fontSize: 13,
  },
  docItemMeta: {
    color: '#996165',
    fontFamily: 'Manrope_400Regular',
    fontSize: 12,
  },
  docItemLink: {
    color: '#ab1e24',
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
  },
  productInfoRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  productInfoColumn: {
    flex: 1,
    gap: 4,
  },
  productGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  productGridItem: {
    width: '48%',
  },
  productImageFrame: {
    width: 110,
    height: 110,
    borderRadius: 10,
    overflow: 'hidden',
    backgroundColor: '#f3dcdd',
  },
  productImageThumb: {
    width: '100%',
    height: '100%',
  },
  productImagePreview: {
    width: '100%',
    height: '100%',
  },
  input: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#e4bcbf',
    backgroundColor: '#fff9f9',
    color: '#4f1c20',
    fontFamily: 'Manrope_400Regular',
    fontSize: 15,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  authLanguageRow: {
    flexDirection: 'row',
    gap: 8,
  },
  authLanguageChip: {
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#e0b8ba',
    backgroundColor: '#fbeeee',
  },
  authLanguageChipActive: {
    borderColor: '#ab1e24',
    backgroundColor: '#f3d0d1',
  },
  authLanguageChipText: {
    color: '#7f1b21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
  },
  restaurantSelectWrap: {
    gap: 8,
  },
  restaurantSelectTrigger: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e0b8ba',
    backgroundColor: '#fff7f7',
    paddingHorizontal: 12,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  restaurantSelectTriggerText: {
    color: '#7f1b21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 13,
  },
  restaurantSelectChevron: {
    color: '#ab1e24',
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
  },
  restaurantSelectList: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e0b8ba',
    backgroundColor: '#fff7f7',
    overflow: 'hidden',
  },
  restaurantSelectItem: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#efd8d9',
  },
  restaurantSelectItemActive: {
    backgroundColor: '#ab1e24',
  },
  restaurantSelectItemText: {
    color: '#7f1b21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 13,
  },
  restaurantSelectItemTextActive: {
    color: '#ffffff',
  },
  error: {
    color: '#b42318',
    fontFamily: 'Manrope_700Bold',
    fontSize: 13,
  },
  rememberRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingTop: 2,
  },
  rememberBox: {
    width: 20,
    height: 20,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#d5aeb0',
    backgroundColor: '#fff9f9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  rememberBoxActive: {
    backgroundColor: '#ab1e24',
    borderColor: '#ab1e24',
  },
  rememberCheck: {
    color: '#f7fffd',
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
  },
  rememberLabel: {
    color: '#7e4a4e',
    fontFamily: 'Manrope_400Regular',
    fontSize: 13,
  },
  primaryButton: {
    backgroundColor: '#ab1e24',
    borderRadius: 14,
    paddingVertical: 13,
    alignItems: 'center',
  },
  buttonDisabled: {
    opacity: 0.65,
  },
  primaryButtonText: {
    color: '#f7fffd',
    fontFamily: 'Manrope_700Bold',
    fontSize: 15,
  },
  linkButton: {
    alignItems: 'center',
    paddingVertical: 6,
  },
  linkText: {
    color: '#ab1e24',
    fontFamily: 'Manrope_700Bold',
    fontSize: 13,
  },
  pillRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  pill: {
    backgroundColor: '#f3dcdd',
    color: '#7f1b21',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
  },
  meta: {
    color: '#7d4a4f',
    fontFamily: 'Manrope_400Regular',
    fontSize: 14,
  },
  secondaryButton: {
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#d39a9d',
    borderRadius: 14,
    paddingVertical: 12,
  },
  secondaryButtonText: {
    color: '#7f1b21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 14,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(36, 12, 14, 0.45)',
    padding: 18,
    justifyContent: 'center',
  },
  modalCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#e4c3c5',
    backgroundColor: '#fff9f9',
    maxHeight: '88%',
  },
  modalContent: {
    padding: 14,
    gap: 10,
  },
  modalHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
});
