import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  page: {
    flex: 1,
  },
  appFrame: {
    flex: 1,
  },
  safeArea: {
    flex: 1,
  },
  keyboardArea: {
    flex: 1,
  },
  keyboardAreaContent: {
    flex: 1,
    zIndex: 1,
  },
  content: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingHorizontal: 20,
    paddingVertical: 28,
    gap: 18,
  },
  contentWithHeader: {
    paddingTop: 12,
  },
  loaderPage: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f6fbfa',
  },
  badge: {
    alignSelf: 'center',
    backgroundColor: '#0f766e',
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  badgeText: {
    color: '#e5fffb',
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
    letterSpacing: 0.4,
  },
  headerBar: {
    height: 72,
    borderRadius: 18,
    marginHorizontal: 12,
    marginTop: 8,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: '#c0d7d1',
    backgroundColor: 'rgba(255,255,255,0.94)',
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 3,
  },
  menuTrigger: {
    width: 42,
    height: 42,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#0f766e',
  },
  menuTriggerText: {
    color: '#f7fffd',
    fontFamily: 'Manrope_700Bold',
    fontSize: 18,
  },
  headerTitleWrap: {
    flex: 1,
    paddingHorizontal: 12,
  },
  headerTitle: {
    color: '#12342f',
    fontFamily: 'Manrope_700Bold',
    fontSize: 16,
  },
  headerSubtitle: {
    color: '#4b6761',
    fontFamily: 'Manrope_400Regular',
    fontSize: 12,
    marginTop: 2,
  },
  headerDot: {
    width: 10,
    height: 10,
    borderRadius: 999,
    backgroundColor: '#16a34a',
  },
  drawerBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(9, 24, 22, 0.3)',
    zIndex: 2,
  },
  drawerPanel: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: 280,
    backgroundColor: '#103632',
    paddingTop: 110,
    paddingHorizontal: 16,
    gap: 10,
    zIndex: 4,
  },
  drawerTitle: {
    color: '#d8fff7',
    fontFamily: 'Manrope_700Bold',
    fontSize: 15,
    marginBottom: 8,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  drawerItem: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#2b5e57',
    backgroundColor: '#174a44',
    paddingVertical: 12,
    paddingHorizontal: 12,
  },
  drawerItemActive: {
    backgroundColor: '#0f766e',
    borderColor: '#5be1cc',
  },
  drawerItemText: {
    color: '#ebfffb',
    fontFamily: 'Manrope_700Bold',
    fontSize: 14,
  },
  languageSection: {
    marginTop: 14,
    borderTopWidth: 1,
    borderTopColor: '#2b5e57',
    paddingTop: 14,
    gap: 8,
  },
  languageTitle: {
    color: '#c5f7ee',
    fontFamily: 'Manrope_700Bold',
    fontSize: 13,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  languageRow: {
    flexDirection: 'row',
    gap: 8,
  },
  languageChip: {
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#2b5e57',
    backgroundColor: '#174a44',
  },
  languageChipActive: {
    backgroundColor: '#0f766e',
    borderColor: '#5be1cc',
  },
  languageChipText: {
    color: '#ebfffb',
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
  },
  listBlock: {
    gap: 8,
    marginTop: 4,
  },
  listItem: {
    color: '#2e4e48',
    fontFamily: 'Manrope_400Regular',
    fontSize: 14,
    lineHeight: 20,
  },
  card: {
    backgroundColor: 'rgba(255,255,255,0.92)',
    borderRadius: 22,
    padding: 18,
    borderWidth: 1,
    borderColor: '#d3e4df',
    gap: 12,
  },
  stackCardWrap: {
    gap: 14,
  },
  uploadCard: {
    backgroundColor: 'rgba(255,255,255,0.92)',
    borderRadius: 22,
    padding: 18,
    borderWidth: 1,
    borderColor: '#d3e4df',
    gap: 10,
  },
  uploadTitle: {
    color: '#183632',
    fontFamily: 'Manrope_700Bold',
    fontSize: 20,
    lineHeight: 26,
  },
  uploadSubtitle: {
    color: '#48645f',
    fontFamily: 'Manrope_400Regular',
    fontSize: 13,
    lineHeight: 18,
  },
  uploadResultBox: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#c7ddd7',
    backgroundColor: '#eef7f4',
    padding: 10,
    gap: 6,
  },
  uploadResultText: {
    color: '#22514a',
    fontFamily: 'Manrope_700Bold',
    fontSize: 13,
  },
  uploadResultLink: {
    color: '#0f766e',
    fontFamily: 'Manrope_400Regular',
    fontSize: 12,
  },
  title: {
    color: '#183632',
    fontFamily: 'Manrope_700Bold',
    fontSize: 24,
    lineHeight: 30,
  },
  subtitle: {
    color: '#4f6963',
    fontFamily: 'Manrope_400Regular',
    fontSize: 13,
  },
  input: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#cfe0db',
    backgroundColor: '#f8fcfb',
    color: '#0f2622',
    fontFamily: 'Manrope_400Regular',
    fontSize: 15,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  authLanguageRow: {
    flexDirection: 'row',
    gap: 8,
  },
  authLanguageChip: {
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#b8d3cc',
    backgroundColor: '#eff8f5',
  },
  authLanguageChipActive: {
    borderColor: '#0f766e',
    backgroundColor: '#d6efea',
  },
  authLanguageChipText: {
    color: '#1d4d45',
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
  },
  error: {
    color: '#b42318',
    fontFamily: 'Manrope_700Bold',
    fontSize: 13,
  },
  rememberRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingTop: 2,
  },
  rememberBox: {
    width: 20,
    height: 20,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#9bbcb4',
    backgroundColor: '#f8fcfb',
    alignItems: 'center',
    justifyContent: 'center',
  },
  rememberBoxActive: {
    backgroundColor: '#0f766e',
    borderColor: '#0f766e',
  },
  rememberCheck: {
    color: '#f7fffd',
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
  },
  rememberLabel: {
    color: '#2f5650',
    fontFamily: 'Manrope_400Regular',
    fontSize: 13,
  },
  primaryButton: {
    backgroundColor: '#0f766e',
    borderRadius: 14,
    paddingVertical: 13,
    alignItems: 'center',
  },
  buttonDisabled: {
    opacity: 0.65,
  },
  primaryButtonText: {
    color: '#f7fffd',
    fontFamily: 'Manrope_700Bold',
    fontSize: 15,
  },
  linkButton: {
    alignItems: 'center',
    paddingVertical: 6,
  },
  linkText: {
    color: '#0f766e',
    fontFamily: 'Manrope_700Bold',
    fontSize: 13,
  },
  pillRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  pill: {
    backgroundColor: '#e7f4ef',
    color: '#1c4f46',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
  },
  meta: {
    color: '#27443f',
    fontFamily: 'Manrope_400Regular',
    fontSize: 14,
  },
  secondaryButton: {
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#a2c8bf',
    borderRadius: 14,
    paddingVertical: 12,
  },
  secondaryButtonText: {
    color: '#20544b',
    fontFamily: 'Manrope_700Bold',
    fontSize: 14,
  },
});
