import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  page: {
    flex: 1,
  },
  pageContent: {
    paddingHorizontal: 24,
    paddingBottom: 28,
    paddingTop: 20,
    gap: 20,
  },
  feedbackState: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    gap: 12,
  },
  feedbackText: {
    color: '#7b4f54',
    fontFamily: 'Manrope_700Bold',
    fontSize: 14,
    textAlign: 'center',
  },
  heroCard: {
    borderRadius: 28,
    borderWidth: 1,
    borderColor: 'rgba(171, 30, 36, 0.1)',
    backgroundColor: '#fffdfb',
    paddingHorizontal: 24,
    paddingVertical: 22,
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 16,
    flexWrap: 'wrap',
  },
  heroTextWrap: {
    flex: 1,
    minWidth: 240,
    gap: 8,
  },
  heroBadge: {
    alignSelf: 'flex-start',
    borderRadius: 999,
    backgroundColor: '#fff2ee',
    color: '#ab1e24',
    fontFamily: 'Manrope_700Bold',
    fontSize: 11,
    overflow: 'hidden',
    paddingHorizontal: 10,
    paddingVertical: 5,
    textTransform: 'uppercase',
  },
  heroTitle: {
    color: '#5f1c21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 32,
  },
  heroSubtitle: {
    color: '#8d5a5f',
    fontFamily: 'Manrope_400Regular',
    fontSize: 14,
    lineHeight: 22,
  },
  scopeCard: {
    minWidth: 220,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(171, 30, 36, 0.1)',
    backgroundColor: '#fff8f5',
    paddingHorizontal: 16,
    paddingVertical: 14,
    gap: 6,
  },
  scopeLabel: {
    color: '#8d5a5f',
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
  },
  scopeValue: {
    color: '#5f1c21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 16,
  },
  metricGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
  },
  metricCard: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(171, 30, 36, 0.1)',
    backgroundColor: '#ffffff',
    paddingHorizontal: 18,
    paddingVertical: 18,
    gap: 10,
    minWidth: 180,
  },
  metricIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 14,
    backgroundColor: '#fff1ef',
    alignItems: 'center',
    justifyContent: 'center',
  },
  metricValue: {
    color: '#5f1c21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 28,
  },
  metricLabel: {
    color: '#8d5a5f',
    fontFamily: 'Manrope_700Bold',
    fontSize: 13,
  },
  emptyCard: {
    borderRadius: 28,
    borderWidth: 1,
    borderColor: 'rgba(171, 30, 36, 0.1)',
    backgroundColor: '#fffdfb',
    paddingHorizontal: 24,
    paddingVertical: 32,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  emptyTitle: {
    color: '#5f1c21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 18,
  },
  emptyText: {
    color: '#8d5a5f',
    fontFamily: 'Manrope_400Regular',
    fontSize: 14,
    lineHeight: 22,
    textAlign: 'center',
    maxWidth: 480,
  },
  sectionCard: {
    borderRadius: 28,
    borderWidth: 1,
    borderColor: 'rgba(171, 30, 36, 0.1)',
    backgroundColor: '#fffdfb',
    paddingHorizontal: 20,
    paddingVertical: 20,
    gap: 18,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
    flexWrap: 'wrap',
  },
  sectionTitle: {
    color: '#5f1c21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 24,
  },
  sectionSubtitle: {
    color: '#8d5a5f',
    fontFamily: 'Manrope_400Regular',
    fontSize: 13,
    lineHeight: 20,
    marginTop: 6,
  },
  storeGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
  },
  storeCard: {
    borderRadius: 22,
    borderWidth: 1,
    borderColor: 'rgba(171, 30, 36, 0.1)',
    backgroundColor: '#ffffff',
    paddingHorizontal: 18,
    paddingVertical: 18,
    gap: 14,
    minWidth: 240,
  },
  storeHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  storeTextWrap: {
    flex: 1,
    gap: 4,
  },
  storeName: {
    color: '#5f1c21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 18,
  },
  storeAddress: {
    color: '#8d5a5f',
    fontFamily: 'Manrope_400Regular',
    fontSize: 12,
    lineHeight: 18,
  },
  storeCountBadge: {
    minWidth: 42,
    height: 42,
    borderRadius: 16,
    backgroundColor: '#fff1ef',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  storeCountValue: {
    color: '#ab1e24',
    fontFamily: 'Manrope_700Bold',
    fontSize: 18,
  },
  storeStatRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  storeStatChip: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(171, 30, 36, 0.08)',
    backgroundColor: '#fff8f5',
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 4,
    minWidth: 86,
  },
  storeStatLabel: {
    color: '#8d5a5f',
    fontFamily: 'Manrope_700Bold',
    fontSize: 11,
  },
  storeStatValue: {
    color: '#5f1c21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 16,
  },
  workplaceChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  workplaceChip: {
    borderRadius: 999,
    backgroundColor: '#fff7f4',
    borderWidth: 1,
    borderColor: 'rgba(171, 30, 36, 0.08)',
    paddingHorizontal: 12,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  workplaceChipLabel: {
    color: '#7b4f54',
    fontFamily: 'Manrope_700Bold',
    fontSize: 11,
  },
  workplaceChipValue: {
    color: '#ab1e24',
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
  },
  managerBlock: {
    borderRadius: 18,
    backgroundColor: '#fff8f5',
    borderWidth: 1,
    borderColor: 'rgba(171, 30, 36, 0.08)',
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 6,
  },
  managerLabel: {
    color: '#8d5a5f',
    fontFamily: 'Manrope_700Bold',
    fontSize: 11,
  },
  managerValue: {
    color: '#5f1c21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 13,
    lineHeight: 20,
  },
  insightGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
  },
  distributionList: {
    gap: 14,
  },
  distributionRow: {
    gap: 8,
  },
  distributionTextWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  distributionLabel: {
    flex: 1,
    color: '#5f1c21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 13,
  },
  distributionValue: {
    color: '#8d5a5f',
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
  },
  distributionTrack: {
    height: 10,
    borderRadius: 999,
    backgroundColor: '#f8e9e5',
    overflow: 'hidden',
  },
  distributionFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: '#ab1e24',
  },
  workplaceSummaryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 14,
  },
  workplaceSummaryCard: {
    flex: 1,
    minWidth: 140,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(171, 30, 36, 0.08)',
    backgroundColor: '#ffffff',
    paddingHorizontal: 16,
    paddingVertical: 18,
    gap: 6,
  },
  workplaceSummaryValue: {
    color: '#5f1c21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 26,
  },
  workplaceSummaryLabel: {
    color: '#8d5a5f',
    fontFamily: 'Manrope_700Bold',
    fontSize: 13,
  },
  rosterFilterBlock: {
    gap: 10,
  },
  rosterFilterLabel: {
    color: '#8d5a5f',
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
  },
  rosterFilterRow: {
    gap: 10,
    paddingRight: 12,
  },
  rosterFilterButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(171, 30, 36, 0.1)',
    backgroundColor: '#fff8f5',
    paddingHorizontal: 14,
    paddingVertical: 10,
    minWidth: 130,
    maxWidth: 220,
  },
  rosterFilterButtonActive: {
    backgroundColor: '#ab1e24',
    borderColor: '#ab1e24',
  },
  rosterFilterButtonText: {
    flex: 1,
    color: '#7b4f54',
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
  },
  rosterFilterButtonTextActive: {
    color: '#ffffff',
  },
  rosterFilterCount: {
    minWidth: 24,
    height: 24,
    borderRadius: 999,
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 6,
  },
  rosterFilterCountActive: {
    backgroundColor: 'rgba(255, 255, 255, 0.18)',
  },
  rosterFilterCountText: {
    color: '#ab1e24',
    fontFamily: 'Manrope_700Bold',
    fontSize: 11,
  },
  rosterFilterCountTextActive: {
    color: '#ffffff',
  },
  rosterSectionCard: {
    borderRadius: 22,
    borderWidth: 1,
    borderColor: 'rgba(171, 30, 36, 0.1)',
    backgroundColor: '#ffffff',
    paddingHorizontal: 16,
    paddingVertical: 16,
    gap: 12,
    minWidth: 260,
  },
  rosterSectionHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(171, 30, 36, 0.08)',
  },
  rosterSectionHeading: {
    flex: 1,
    minWidth: 0,
  },
  rosterHeaderStats: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
  },
  rosterStoreName: {
    color: '#5f1c21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 16,
  },
  rosterStoreAddress: {
    color: '#8d5a5f',
    fontFamily: 'Manrope_400Regular',
    fontSize: 12,
    marginTop: 4,
  },
  rosterHeaderBadge: {
    minWidth: 68,
    borderRadius: 16,
    backgroundColor: '#fff8f5',
    borderWidth: 1,
    borderColor: 'rgba(171, 30, 36, 0.08)',
    paddingHorizontal: 10,
    paddingVertical: 8,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
  },
  rosterHeaderBadgeValue: {
    color: '#ab1e24',
    fontFamily: 'Manrope_700Bold',
    fontSize: 15,
  },
  rosterHeaderBadgeLabel: {
    color: '#8d5a5f',
    fontFamily: 'Manrope_700Bold',
    fontSize: 10,
  },
  rosterList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  rosterEmptyState: {
    borderRadius: 16,
    backgroundColor: '#fff8f5',
    borderWidth: 1,
    borderColor: 'rgba(171, 30, 36, 0.08)',
    paddingHorizontal: 14,
    paddingVertical: 18,
  },
  rosterEmptyText: {
    color: '#8d5a5f',
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
  },
  rosterCompactCard: {
    borderRadius: 18,
    backgroundColor: '#fff8f5',
    borderWidth: 1,
    borderColor: 'rgba(171, 30, 36, 0.08)',
    paddingHorizontal: 12,
    paddingVertical: 12,
    gap: 10,
    minWidth: 160,
  },
  rosterCardTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  rosterOrderBadge: {
    minWidth: 28,
    height: 28,
    borderRadius: 999,
    backgroundColor: '#ab1e24',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  rosterOrderBadgeText: {
    color: '#ffffff',
    fontFamily: 'Manrope_700Bold',
    fontSize: 11,
  },
  avatarWrap: {
    width: 34,
    height: 34,
    borderRadius: 11,
    backgroundColor: '#f7e8e0',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  avatarImage: {
    width: '100%',
    height: '100%',
  },
  avatarText: {
    color: '#ab1e24',
    fontFamily: 'Manrope_700Bold',
    fontSize: 16,
  },
  rosterBody: {
    gap: 3,
  },
  rosterName: {
    color: '#5f1c21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 13,
  },
  rosterEmail: {
    color: '#8d5a5f',
    fontFamily: 'Manrope_400Regular',
    fontSize: 10,
  },
  rosterMetaStack: {
    gap: 6,
  },
  rosterMetaLine: {
    borderRadius: 12,
    backgroundColor: '#fffdfb',
    borderWidth: 1,
    borderColor: 'rgba(171, 30, 36, 0.08)',
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 2,
  },
  rosterFactLabel: {
    color: '#8d5a5f',
    fontFamily: 'Manrope_700Bold',
    fontSize: 10,
  },
  rosterFactValue: {
    color: '#5f1c21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 11,
    lineHeight: 16,
  },
});
