import { StyleSheet } from 'react-native';

const CARD_BORDER = 'rgba(171, 30, 36, 0.18)';
const CARD_BORDER_SOFT = 'rgba(171, 30, 36, 0.14)';
const EARTH_BORDER = 'rgba(113, 72, 67, 0.18)';
const EARTH_BORDER_SOFT = 'rgba(113, 72, 67, 0.14)';

export const styles = StyleSheet.create({
  page: {
    flex: 1,
  },
  pageContent: {
    paddingHorizontal: 24,
    paddingBottom: 28,
    paddingTop: 20,
    gap: 20,
  },
  feedbackState: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    gap: 12,
  },
  feedbackText: {
    color: '#7b4f54',
    fontFamily: 'Manrope_700Bold',
    fontSize: 14,
    textAlign: 'center',
  },
  heroCard: {
    borderRadius: 28,
    borderWidth: 1,
    borderColor: CARD_BORDER,
    backgroundColor: '#fffdfb',
    paddingHorizontal: 24,
    paddingVertical: 22,
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 16,
    flexWrap: 'wrap',
  },
  heroTextWrap: {
    flex: 1,
    minWidth: 240,
    gap: 8,
  },
  heroBadge: {
    alignSelf: 'flex-start',
    borderRadius: 999,
    backgroundColor: '#fff2ee',
    color: '#ab1e24',
    fontFamily: 'Manrope_700Bold',
    fontSize: 11,
    overflow: 'hidden',
    paddingHorizontal: 10,
    paddingVertical: 5,
    textTransform: 'uppercase',
  },
  heroTitle: {
    color: '#5f1c21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 32,
  },
  heroSubtitle: {
    color: '#8d5a5f',
    fontFamily: 'Manrope_400Regular',
    fontSize: 14,
    lineHeight: 22,
  },
  scopeCard: {
    minWidth: 220,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: CARD_BORDER,
    backgroundColor: '#fff8f5',
    paddingHorizontal: 16,
    paddingVertical: 14,
    gap: 6,
  },
  scopeLabel: {
    color: '#8d5a5f',
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
  },
  scopeValue: {
    color: '#5f1c21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 16,
  },
  metricGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
  },
  metricCard: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: CARD_BORDER,
    backgroundColor: '#ffffff',
    paddingHorizontal: 18,
    paddingVertical: 18,
    gap: 10,
    minWidth: 180,
  },
  metricIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 14,
    backgroundColor: '#fff1ef',
    alignItems: 'center',
    justifyContent: 'center',
  },
  metricValue: {
    color: '#5f1c21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 28,
  },
  metricLabel: {
    color: '#8d5a5f',
    fontFamily: 'Manrope_700Bold',
    fontSize: 13,
  },
  emptyCard: {
    borderRadius: 28,
    borderWidth: 1,
    borderColor: CARD_BORDER,
    backgroundColor: '#fffdfb',
    paddingHorizontal: 24,
    paddingVertical: 32,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  emptyTitle: {
    color: '#5f1c21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 18,
  },
  emptyText: {
    color: '#8d5a5f',
    fontFamily: 'Manrope_400Regular',
    fontSize: 14,
    lineHeight: 22,
    textAlign: 'center',
    maxWidth: 480,
  },
  sectionCard: {
    borderRadius: 28,
    borderWidth: 1,
    borderColor: CARD_BORDER,
    backgroundColor: '#fffdfb',
    paddingHorizontal: 20,
    paddingVertical: 20,
    gap: 18,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
    flexWrap: 'wrap',
  },
  sectionTitle: {
    color: '#5f1c21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 24,
  },
  sectionSubtitle: {
    color: '#8d5a5f',
    fontFamily: 'Manrope_400Regular',
    fontSize: 13,
    lineHeight: 20,
    marginTop: 6,
  },
  storeGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
  },
  storeCard: {
    borderRadius: 22,
    borderWidth: 1,
    borderColor: CARD_BORDER,
    backgroundColor: '#ffffff',
    paddingHorizontal: 18,
    paddingVertical: 18,
    gap: 14,
    minWidth: 240,
  },
  storeHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  storeTextWrap: {
    flex: 1,
    gap: 4,
  },
  storeName: {
    color: '#5f1c21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 18,
  },
  storeAddress: {
    color: '#8d5a5f',
    fontFamily: 'Manrope_400Regular',
    fontSize: 12,
    lineHeight: 18,
  },
  storeCountBadge: {
    minWidth: 54,
    borderRadius: 16,
    backgroundColor: '#fff1ef',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 2,
  },
  storeCountLabel: {
    color: '#8d5a5f',
    fontFamily: 'Manrope_700Bold',
    fontSize: 9,
    textTransform: 'uppercase',
  },
  storeCountValue: {
    color: '#ab1e24',
    fontFamily: 'Manrope_700Bold',
    fontSize: 18,
  },
  storeStatRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  storeStatChip: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: CARD_BORDER_SOFT,
    backgroundColor: '#fff8f5',
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 4,
    minWidth: 86,
  },
  storeStatLabel: {
    color: '#8d5a5f',
    fontFamily: 'Manrope_700Bold',
    fontSize: 11,
  },
  storeStatValue: {
    color: '#5f1c21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 16,
  },
  workplaceChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  workplaceChip: {
    borderRadius: 999,
    backgroundColor: '#fff7f4',
    borderWidth: 1,
    borderColor: CARD_BORDER_SOFT,
    paddingHorizontal: 12,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  workplaceChipLabel: {
    color: '#7b4f54',
    fontFamily: 'Manrope_700Bold',
    fontSize: 11,
  },
  workplaceChipValue: {
    color: '#ab1e24',
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
  },
  managerBlock: {
    borderRadius: 18,
    backgroundColor: '#fff8f5',
    borderWidth: 1,
    borderColor: CARD_BORDER_SOFT,
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 6,
  },
  managerLabel: {
    color: '#8d5a5f',
    fontFamily: 'Manrope_700Bold',
    fontSize: 11,
  },
  managerValue: {
    color: '#5f1c21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 13,
    lineHeight: 20,
  },
  insightGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
  },
  distributionList: {
    gap: 14,
  },
  distributionRow: {
    gap: 8,
  },
  distributionTextWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  distributionLabel: {
    flex: 1,
    color: '#5f1c21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 13,
  },
  distributionValue: {
    color: '#8d5a5f',
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
  },
  distributionTrack: {
    height: 10,
    borderRadius: 999,
    backgroundColor: '#f8e9e5',
    overflow: 'hidden',
  },
  distributionFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: '#ab1e24',
  },
  workplaceSummaryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 14,
  },
  workplaceSummaryCard: {
    flex: 1,
    minWidth: 140,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: CARD_BORDER_SOFT,
    backgroundColor: '#ffffff',
    paddingHorizontal: 16,
    paddingVertical: 18,
    gap: 6,
  },
  workplaceSummaryValue: {
    color: '#5f1c21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 26,
  },
  workplaceSummaryLabel: {
    color: '#8d5a5f',
    fontFamily: 'Manrope_700Bold',
    fontSize: 13,
  },
  rosterFilterBlock: {
    gap: 10,
  },
  rosterFilterLabel: {
    color: '#8d5a5f',
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
  },
  rosterFilterRow: {
    gap: 10,
    paddingRight: 12,
  },
  rosterFilterButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(171, 30, 36, 0.1)',
    backgroundColor: '#fff8f5',
    paddingHorizontal: 14,
    paddingVertical: 10,
    minWidth: 130,
    maxWidth: 220,
  },
  rosterFilterButtonActive: {
    backgroundColor: '#ab1e24',
    borderColor: '#ab1e24',
  },
  rosterFilterButtonText: {
    flex: 1,
    color: '#7b4f54',
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
  },
  rosterFilterButtonTextActive: {
    color: '#ffffff',
  },
  rosterFilterCount: {
    minWidth: 24,
    height: 24,
    borderRadius: 999,
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 6,
  },
  rosterFilterCountActive: {
    backgroundColor: 'rgba(255, 255, 255, 0.18)',
  },
  rosterFilterCountText: {
    color: '#ab1e24',
    fontFamily: 'Manrope_700Bold',
    fontSize: 11,
  },
  rosterFilterCountTextActive: {
    color: '#ffffff',
  },
  rosterSectionCard: {
    borderRadius: 22,
    borderWidth: 1,
    borderColor: CARD_BORDER,
    backgroundColor: '#ffffff',
    paddingHorizontal: 16,
    paddingVertical: 16,
    gap: 12,
    minWidth: 260,
  },
  rosterSectionHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: CARD_BORDER_SOFT,
  },
  rosterSectionHeading: {
    flex: 1,
    minWidth: 0,
  },
  rosterHeaderStats: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
  },
  rosterStoreName: {
    color: '#5f1c21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 16,
  },
  rosterStoreAddress: {
    color: '#8d5a5f',
    fontFamily: 'Manrope_400Regular',
    fontSize: 12,
    marginTop: 4,
  },
  rosterHeaderBadge: {
    minWidth: 68,
    borderRadius: 16,
    backgroundColor: '#fff8f5',
    borderWidth: 1,
    borderColor: CARD_BORDER_SOFT,
    paddingHorizontal: 10,
    paddingVertical: 8,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
  },
  rosterHeaderBadgeValue: {
    color: '#ab1e24',
    fontFamily: 'Manrope_700Bold',
    fontSize: 15,
  },
  rosterHeaderBadgeLabel: {
    color: '#8d5a5f',
    fontFamily: 'Manrope_700Bold',
    fontSize: 10,
  },
  rosterPaginationBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    flexWrap: 'wrap',
  },
  rosterPaginationText: {
    color: '#8d5a5f',
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
  },
  rosterPaginationControls: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
  },
  rosterPaginationButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(171, 30, 36, 0.1)',
    backgroundColor: '#fff8f5',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  rosterPaginationButtonDisabled: {
    borderColor: 'rgba(171, 30, 36, 0.06)',
    backgroundColor: '#f8f1ee',
  },
  rosterPaginationButtonText: {
    color: '#ab1e24',
    fontFamily: 'Manrope_700Bold',
    fontSize: 11,
  },
  rosterPaginationButtonTextDisabled: {
    color: '#c9acab',
  },
  rosterColumnsWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  rosterColumn: {
    gap: 12,
  },
  rosterEmptyState: {
    borderRadius: 16,
    backgroundColor: '#fff8f5',
    borderWidth: 1,
    borderColor: CARD_BORDER_SOFT,
    paddingHorizontal: 14,
    paddingVertical: 18,
  },
  rosterEmptyText: {
    color: '#8d5a5f',
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
  },
  rosterCompactCard: {
    borderRadius: 12,
    backgroundColor: '#fffdfc',
    borderWidth: 1,
    borderColor: EARTH_BORDER,
    paddingHorizontal: 10,
    paddingVertical: 10,
    gap: 10,
  },
  rosterCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    minWidth: 0,
  },
  rosterOrderBadge: {
    minWidth: 24,
    height: 24,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(171, 30, 36, 0.16)',
    backgroundColor: '#fff7f5',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 6,
  },
  rosterOrderBadgeText: {
    color: '#8b363b',
    fontFamily: 'Manrope_700Bold',
    fontSize: 10,
  },
  avatarWrap: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: '#f4ebe8',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  avatarImage: {
    width: '100%',
    height: '100%',
  },
  avatarText: {
    color: '#ab1e24',
    fontFamily: 'Manrope_700Bold',
    fontSize: 14,
  },
  rosterBody: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  rosterName: {
    color: '#5f1c21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
  },
  rosterEmail: {
    color: '#8e6b67',
    fontFamily: 'Manrope_400Regular',
    fontSize: 9,
  },
  rosterInfoPanel: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: EARTH_BORDER_SOFT,
    backgroundColor: '#faf7f5',
    paddingHorizontal: 8,
    paddingVertical: 8,
    gap: 8,
  },
  rosterInfoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  rosterInfoItem: {
    flexGrow: 1,
    flexBasis: 92,
    gap: 2,
  },
  rosterInfoItemWide: {
    flexBasis: 100,
  },
  rosterInfoLabel: {
    color: '#9b7e79',
    fontFamily: 'Manrope_700Bold',
    fontSize: 9,
    textTransform: 'uppercase',
  },
  rosterInfoValue: {
    color: '#5f1c21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 10,
    lineHeight: 14,
  },
  rosterStatusBadge: {
    alignSelf: 'flex-start',
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(171, 30, 36, 0.14)',
    backgroundColor: '#fff7f5',
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  rosterStatusBadgeText: {
    color: '#8b363b',
    fontFamily: 'Manrope_700Bold',
    fontSize: 9,
  },
});
