import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  uploadCard: {
    backgroundColor: '#fffdfb',
    borderRadius: 24,
    padding: 18,
    borderWidth: 1,
    borderColor: 'rgba(171, 30, 36, 0.12)',
    gap: 12,
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  headerMain: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
  },
  headerIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ab1e24',
  },
  statusPill: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(171, 30, 36, 0.14)',
    backgroundColor: '#fff2ef',
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  statusPillText: {
    color: '#ab1e24',
    fontFamily: 'Manrope_700Bold',
    fontSize: 10,
  },
  introStrip: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(171, 30, 36, 0.08)',
    backgroundColor: '#fff5f2',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  uploadTitle: {
    color: '#5f1c21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 18,
  },
  uploadSubtitle: {
    color: '#8d5a5f',
    fontFamily: 'Manrope_400Regular',
    fontSize: 13,
    lineHeight: 18,
  },
  uploadFieldTitle: {
    color: '#7a3036',
    fontFamily: 'Manrope_700Bold',
    fontSize: 13,
  },
  body: {
    gap: 12,
    flex: 1,
  },
  fieldBlock: {
    gap: 8,
  },
  uploadChipWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  uploadChip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#dfb0b2',
    backgroundColor: '#fffafa',
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  uploadChipActive: {
    borderColor: '#b75d62',
    backgroundColor: '#f8e2e4',
  },
  uploadChipText: {
    color: '#8d5458',
    fontFamily: 'Manrope_700Bold',
    fontSize: 11,
  },
  uploadChipTextActive: {
    color: '#7a181d',
  },
  docEmpty: {
    color: '#a06a6f',
    fontFamily: 'Manrope_400Regular',
    fontSize: 13,
  },
  input: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(171, 30, 36, 0.12)',
    backgroundColor: '#ffffff',
    color: '#5f1c21',
    fontFamily: 'Manrope_400Regular',
    fontSize: 15,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  error: {
    color: '#b42318',
    fontFamily: 'Manrope_700Bold',
    fontSize: 13,
  },
  footer: {
    marginTop: 'auto',
  },
  primaryButton: {
    borderRadius: 18,
    paddingVertical: 14,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#97161c',
    backgroundColor: '#ab1e24',
  },
  buttonDisabled: {
    opacity: 0.65,
  },
  primaryButtonText: {
    color: '#ffffff',
    fontFamily: 'Manrope_700Bold',
    fontSize: 14,
  },
  secondaryButton: {
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#d39a9d',
    borderRadius: 14,
    paddingVertical: 12,
    backgroundColor: '#fffafa',
  },
  secondaryButtonText: {
    color: '#7f1b21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 14,
  },
});
