import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  card: {
    backgroundColor: 'rgba(255,255,255,0.92)',
    borderRadius: 22,
    padding: 18,
    borderWidth: 1,
    borderColor: '#e8c3c4',
    gap: 12,
  },
  title: {
    color: '#7a181d',
    fontFamily: 'Manrope_700Bold',
    fontSize: 24,
    lineHeight: 30,
  },
  subtitle: {
    color: '#8d5458',
    fontFamily: 'Manrope_400Regular',
    fontSize: 13,
  },
  trainingTabRow: {
    flexDirection: 'row',
    gap: 8,
    paddingVertical: 4,
  },
  trainingTab: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#dfb0b2',
    backgroundColor: '#f9ebec',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  trainingTabActive: {
    backgroundColor: '#ab1e24',
    borderColor: '#ab1e24',
  },
  trainingTabText: {
    color: '#7f1b21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 13,
  },
  trainingTabTextActive: {
    color: '#ffffff',
  },
  docBlock: {
    marginTop: 8,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#e4c3c5',
    backgroundColor: '#fff7f7',
    padding: 12,
    gap: 8,
  },
  docBlockTitle: {
    color: '#7f1b21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 14,
  },
  workflowCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e8b3b6',
    backgroundColor: '#fff0f1',
    padding: 10,
    gap: 8,
    marginBottom: 4,
  },
  workflowTitle: {
    color: '#7f1b21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 13,
  },
  workflowHint: {
    color: '#8f5559',
    fontFamily: 'Manrope_400Regular',
    fontSize: 12,
    lineHeight: 17,
  },
  quizLanguageRow: {
    gap: 6,
  },
  quizLanguageLabel: {
    color: '#8f5559',
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
  },
  quizLanguageChipRow: {
    flexDirection: 'row',
    gap: 8,
  },
  quizLanguageChip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#d8a1a5',
    backgroundColor: '#fff8f8',
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  quizLanguageChipActive: {
    borderColor: '#ab1e24',
    backgroundColor: '#ab1e24',
  },
  quizLanguageChipText: {
    color: '#7f1b21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 11,
  },
  quizLanguageChipTextActive: {
    color: '#ffffff',
  },
  workflowStepRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  workflowStepBadge: {
    width: 20,
    height: 20,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#dca4a7',
    backgroundColor: '#ffffff',
  },
  workflowStepBadgeDone: {
    borderColor: '#ab1e24',
    backgroundColor: '#ab1e24',
  },
  workflowStepBadgeText: {
    color: '#7f1b21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 11,
  },
  workflowStepBadgeTextDone: {
    color: '#ffffff',
  },
  workflowStepText: {
    color: '#7f1b21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
  },
  quizActionButton: {
    marginTop: 2,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#ab1e24',
    backgroundColor: '#ab1e24',
    paddingHorizontal: 12,
    paddingVertical: 9,
    alignItems: 'center',
  },
  quizActionButtonDisabled: {
    borderColor: '#d6abaf',
    backgroundColor: '#d6abaf',
  },
  quizActionButtonText: {
    color: '#ffffff',
    fontFamily: 'Manrope_700Bold',
    fontSize: 13,
  },
  workflowStatusText: {
    color: '#8f5559',
    fontFamily: 'Manrope_400Regular',
    fontSize: 12,
  },
  docEmpty: {
    color: '#a06a6f',
    fontFamily: 'Manrope_400Regular',
    fontSize: 13,
  },
  docItem: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#edd4d5',
    backgroundColor: '#ffffff',
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 6,
  },
  docItemActive: {
    borderColor: '#ab1e24',
    backgroundColor: '#fff1f1',
  },
  docItemTitle: {
    color: '#7a2328',
    fontFamily: 'Manrope_700Bold',
    fontSize: 13,
  },
  docItemMeta: {
    color: '#996165',
    fontFamily: 'Manrope_400Regular',
    fontSize: 12,
  },
  docActionButton: {
    alignSelf: 'flex-start',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#d89b9f',
    backgroundColor: '#fff8f8',
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  docActionButtonText: {
    color: '#7f1b21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
  },
  videoSelectorGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    paddingTop: 6,
  },
  videoSelectorCard: {
    width: '100%',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#efcbcc',
    backgroundColor: 'rgba(255,255,255,0.94)',
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 4,
  },
  videoSelectorCardTitle: {
    color: '#7f1b21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
    lineHeight: 16,
  },
  videoSelectorCardMeta: {
    color: '#996165',
    fontFamily: 'Manrope_400Regular',
    fontSize: 11,
  },
  error: {
    color: '#b42318',
    fontFamily: 'Manrope_700Bold',
    fontSize: 13,
  },
  videoModalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.58)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
  },
  videoModalCard: {
    width: '100%',
    maxWidth: 760,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#4b1d1f',
    backgroundColor: '#190a0c',
    padding: 12,
    gap: 10,
  },
  previewModalCard: {
    width: '100%',
    maxWidth: 960,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#e8c3c4',
    backgroundColor: '#fffafb',
    padding: 14,
    gap: 12,
  },
  previewModalHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  previewModalTextBlock: {
    flex: 1,
    gap: 4,
  },
  previewModalTitle: {
    color: '#7a181d',
    fontFamily: 'Manrope_700Bold',
    fontSize: 15,
  },
  previewModalHint: {
    color: '#8d5458',
    fontFamily: 'Manrope_400Regular',
    fontSize: 12,
    lineHeight: 17,
  },
  previewModalCloseButton: {
    width: 32,
    height: 32,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#dfb0b2',
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  previewModalCloseText: {
    color: '#7f1b21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 14,
  },
  previewFrameShell: {
    height: 640,
    borderRadius: 14,
    overflow: 'hidden',
    backgroundColor: '#ffffff',
  },
  videoModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  videoModalTitle: {
    flex: 1,
    color: '#fff7f7',
    fontFamily: 'Manrope_700Bold',
    fontSize: 13,
  },
  videoModalCloseButton: {
    width: 30,
    height: 30,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#5f2b2f',
    backgroundColor: '#2b1013',
    alignItems: 'center',
    justifyContent: 'center',
  },
  videoModalCloseText: {
    color: '#ffffff',
    fontFamily: 'Manrope_700Bold',
    fontSize: 14,
  },
  videoPlayerShell: {
    alignSelf: 'center',
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: '#000000',
  },
  videoPlayer: {
    width: '100%',
    height: '100%',
    backgroundColor: '#000000',
  },
});
