import { StyleSheet } from 'react-native';

const BORDER = 'rgba(171, 30, 36, 0.12)';
const SOFT_BORDER = 'rgba(171, 30, 36, 0.08)';
const CARD = '#fffdfb';
const PANEL = '#ffffff';
const BRAND = '#ab1e24';
const BRAND_SOFT = '#fff3ef';
const TEXT = '#5f1c21';
const MUTED = '#8d5a5f';

export const styles = StyleSheet.create({
  pageRoot: {
    flex: 1,
  },
  pageScroll: {
    flex: 1,
  },
  pageContent: {
    gap: 18,
    paddingBottom: 24,
  },
  heroCard: {
    borderRadius: 28,
    borderWidth: 1,
    borderColor: BORDER,
    backgroundColor: CARD,
    padding: 20,
    gap: 16,
  },
  heroHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 14,
    flexWrap: 'wrap',
  },
  heroCopy: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  title: {
    color: TEXT,
    fontFamily: 'Manrope_700Bold',
    fontSize: 28,
    lineHeight: 34,
  },
  subtitle: {
    color: MUTED,
    fontFamily: 'Manrope_400Regular',
    fontSize: 13,
    lineHeight: 19,
  },
  heroBadgeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
    gap: 10,
  },
  heroBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: SOFT_BORDER,
    backgroundColor: BRAND_SOFT,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  heroBadgeText: {
    color: BRAND,
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
  },
  heroStatsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  heroStatCard: {
    minWidth: 140,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: SOFT_BORDER,
    backgroundColor: PANEL,
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 3,
  },
  heroStatValue: {
    color: TEXT,
    fontFamily: 'Manrope_700Bold',
    fontSize: 24,
    lineHeight: 28,
  },
  heroStatLabel: {
    color: MUTED,
    fontFamily: 'Manrope_700Bold',
    fontSize: 11,
  },
  trainingLayout: {
    gap: 18,
  },
  trainingLayoutWide: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  controlColumn: {
    gap: 18,
  },
  controlColumnWide: {
    width: 340,
    flexShrink: 0,
  },
  resourceColumn: {
    minWidth: 0,
  },
  resourceColumnWide: {
    flex: 1,
  },
  surfaceCard: {
    borderRadius: 26,
    borderWidth: 1,
    borderColor: BORDER,
    backgroundColor: CARD,
    padding: 18,
    gap: 16,
  },
  surfaceHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  surfaceHeaderCopy: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  surfaceEyebrow: {
    color: MUTED,
    fontFamily: 'Manrope_700Bold',
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  surfaceTitle: {
    color: TEXT,
    fontFamily: 'Manrope_700Bold',
    fontSize: 20,
    lineHeight: 26,
  },
  surfaceSubtitle: {
    color: MUTED,
    fontFamily: 'Manrope_400Regular',
    fontSize: 12,
    lineHeight: 18,
  },
  surfaceCountPill: {
    minWidth: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 999,
    borderWidth: 1,
    borderColor: SOFT_BORDER,
    backgroundColor: BRAND_SOFT,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  surfaceCountText: {
    color: BRAND,
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
  },
  pillRow: {
    flexDirection: 'row',
    gap: 8,
    paddingVertical: 2,
  },
  pill: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: SOFT_BORDER,
    backgroundColor: '#ffffff',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  pillActive: {
    borderColor: BRAND,
    backgroundColor: BRAND,
  },
  pillText: {
    color: '#7f1b21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
  },
  pillTextActive: {
    color: '#ffffff',
  },
  quizCard: {
    borderRadius: 26,
    borderWidth: 1,
    borderColor: BORDER,
    backgroundColor: CARD,
    padding: 18,
    gap: 14,
  },
  quizHeaderRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  quizHeaderCopy: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  quizTitle: {
    color: TEXT,
    fontFamily: 'Manrope_700Bold',
    fontSize: 18,
  },
  quizHint: {
    color: MUTED,
    fontFamily: 'Manrope_400Regular',
    fontSize: 12,
    lineHeight: 18,
  },
  quizActionButton: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: BRAND,
    backgroundColor: BRAND,
    paddingHorizontal: 14,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  quizActionButtonDisabled: {
    borderColor: '#d8afb2',
    backgroundColor: '#d8afb2',
  },
  quizActionButtonText: {
    color: '#ffffff',
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
  },
  quizLanguageRow: {
    gap: 8,
  },
  quizLanguageLabel: {
    color: '#8a4f53',
    fontFamily: 'Manrope_700Bold',
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  quizLanguageChipRow: {
    flexDirection: 'row',
    gap: 8,
  },
  quizLanguageChip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: SOFT_BORDER,
    backgroundColor: '#ffffff',
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  quizLanguageChipActive: {
    borderColor: BRAND,
    backgroundColor: BRAND_SOFT,
  },
  quizLanguageChipText: {
    color: '#7f1b21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 11,
  },
  quizLanguageChipTextActive: {
    color: BRAND,
  },
  quizStatusText: {
    color: MUTED,
    fontFamily: 'Manrope_400Regular',
    fontSize: 12,
    lineHeight: 18,
  },
  searchWrap: {
    gap: 8,
  },
  searchShell: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: SOFT_BORDER,
    backgroundColor: '#ffffff',
    paddingHorizontal: 12,
  },
  searchInput: {
    flex: 1,
    minWidth: 0,
    color: TEXT,
    fontFamily: 'Manrope_400Regular',
    fontSize: 14,
    paddingVertical: 12,
  },
  contentSplit: {
    gap: 16,
  },
  contentSplitWide: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  taskListWrap: {
    borderRadius: 22,
    borderWidth: 1,
    borderColor: SOFT_BORDER,
    backgroundColor: PANEL,
    padding: 14,
    gap: 12,
  },
  taskListWrapWide: {
    flex: 0.5,
  },
  taskListTitle: {
    color: TEXT,
    fontFamily: 'Manrope_700Bold',
    fontSize: 16,
  },
  taskList: {
    gap: 10,
  },
  taskCard: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: SOFT_BORDER,
    backgroundColor: '#fffdfb',
    padding: 14,
    gap: 12,
  },
  taskCardActive: {
    borderColor: BRAND,
    backgroundColor: '#fff7f4',
  },
  taskCardHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  taskCardIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: SOFT_BORDER,
    backgroundColor: BRAND_SOFT,
    alignItems: 'center',
    justifyContent: 'center',
  },
  taskCardCopy: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  taskCardTitle: {
    color: TEXT,
    fontFamily: 'Manrope_700Bold',
    fontSize: 14,
    lineHeight: 20,
  },
  taskMeta: {
    color: MUTED,
    fontFamily: 'Manrope_400Regular',
    fontSize: 12,
    lineHeight: 17,
  },
  taskBadgeColumn: {
    alignItems: 'flex-end',
    gap: 8,
  },
  taskTypeBadge: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: SOFT_BORDER,
    backgroundColor: BRAND_SOFT,
    paddingHorizontal: 9,
    paddingVertical: 5,
  },
  taskTypeBadgeText: {
    color: BRAND,
    fontFamily: 'Manrope_700Bold',
    fontSize: 10,
  },
  taskStatusBadge: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: SOFT_BORDER,
    backgroundColor: '#fffafa',
    paddingHorizontal: 9,
    paddingVertical: 5,
  },
  taskStatusBadgeDone: {
    borderColor: 'rgba(14, 122, 76, 0.18)',
    backgroundColor: '#e8f9f1',
  },
  taskStatusText: {
    color: MUTED,
    fontFamily: 'Manrope_700Bold',
    fontSize: 10,
  },
  taskStatusTextDone: {
    color: '#0e7a4c',
  },
  taskActionsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  taskActionButton: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: SOFT_BORDER,
    backgroundColor: '#ffffff',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  taskActionButtonText: {
    color: '#7f1b21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 11,
  },
  taskCompletionButton: {
    backgroundColor: '#fff6f7',
  },
  taskCompletionButtonDone: {
    borderColor: 'rgba(14, 122, 76, 0.18)',
    backgroundColor: '#e8f9f1',
  },
  taskCompletionButtonTextDone: {
    color: '#0e7a4c',
  },
  previewWrap: {
    borderRadius: 22,
    borderWidth: 1,
    borderColor: SOFT_BORDER,
    backgroundColor: PANEL,
    padding: 14,
    gap: 12,
  },
  previewWrapSide: {
    flex: 0.5,
    minWidth: 420,
  },
  previewWrapBelow: {
    width: '100%',
  },
  previewHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  previewHeaderCopy: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  previewTitle: {
    color: TEXT,
    fontFamily: 'Manrope_700Bold',
    fontSize: 16,
    lineHeight: 22,
  },
  previewHint: {
    color: MUTED,
    fontFamily: 'Manrope_400Regular',
    fontSize: 12,
    lineHeight: 17,
  },
  previewControlsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  previewControlButton: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: SOFT_BORDER,
    backgroundColor: BRAND_SOFT,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  previewControlButtonText: {
    color: BRAND,
    fontFamily: 'Manrope_700Bold',
    fontSize: 11,
  },
  previewFrameShell: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: SOFT_BORDER,
    backgroundColor: '#ffffff',
    overflow: 'hidden',
  },
  previewEmptyWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  previewEmptyText: {
    color: MUTED,
    fontFamily: 'Manrope_400Regular',
    fontSize: 12,
    textAlign: 'center',
    lineHeight: 18,
  },
  emptyStateCard: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: SOFT_BORDER,
    backgroundColor: CARD,
    padding: 18,
  },
  emptyStateCardInner: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: SOFT_BORDER,
    backgroundColor: '#fff8f5',
    paddingHorizontal: 14,
    paddingVertical: 16,
  },
  emptyText: {
    color: MUTED,
    fontFamily: 'Manrope_400Regular',
    fontSize: 13,
    lineHeight: 19,
  },
  error: {
    color: '#b42318',
    fontFamily: 'Manrope_700Bold',
    fontSize: 13,
    lineHeight: 18,
  },
  previewFullscreenBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(15, 6, 7, 0.84)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 18,
  },
  previewFullscreenCard: {
    width: '100%',
    maxWidth: 1360,
    height: '92%',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#4b1d1f',
    backgroundColor: '#fffdfd',
    padding: 14,
    gap: 12,
  },
  previewFullscreenHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  previewFullscreenTitle: {
    flex: 1,
    color: TEXT,
    fontFamily: 'Manrope_700Bold',
    fontSize: 14,
  },
  previewFullscreenFrameShell: {
    flex: 1,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: SOFT_BORDER,
    overflow: 'hidden',
    backgroundColor: '#ffffff',
  },
  videoModalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.58)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
  },
  videoModalCard: {
    width: '100%',
    maxWidth: 760,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#4b1d1f',
    backgroundColor: '#190a0c',
    padding: 14,
    gap: 12,
  },
  videoModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  videoModalTitle: {
    flex: 1,
    color: '#fff7f7',
    fontFamily: 'Manrope_700Bold',
    fontSize: 14,
    lineHeight: 20,
  },
  videoModalCloseButton: {
    width: 32,
    height: 32,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#5f2b2f',
    backgroundColor: '#2b1013',
    alignItems: 'center',
    justifyContent: 'center',
  },
  videoModalCloseText: {
    color: '#ffffff',
    fontFamily: 'Manrope_700Bold',
    fontSize: 14,
  },
  videoPlayerShell: {
    alignSelf: 'center',
    borderRadius: 14,
    overflow: 'hidden',
    backgroundColor: '#000000',
  },
  videoPlayer: {
    width: '100%',
    height: '100%',
    backgroundColor: '#000000',
  },
});
