import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  pageStack: {
    gap: 18,
  },
  heroCard: {
    backgroundColor: 'rgba(255, 251, 247, 0.94)',
    borderRadius: 28,
    padding: 22,
    borderWidth: 1,
    borderColor: 'rgba(142, 34, 40, 0.12)',
    gap: 18,
  },
  heroCardWide: {
    flexDirection: 'row',
    alignItems: 'stretch',
  },
  heroIdentity: {
    gap: 16,
  },
  heroIdentityWide: {
    flex: 1.1,
    paddingRight: 10,
  },
  eyebrow: {
    color: '#8d5a5f',
    fontFamily: 'Manrope_700Bold',
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  heroTitle: {
    color: '#5f1c21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 30,
    lineHeight: 36,
  },
  heroSubtitle: {
    color: '#8d5a5f',
    fontFamily: 'Manrope_400Regular',
    fontSize: 14,
    lineHeight: 20,
  },
  heroMeta: {
    color: '#724448',
    fontFamily: 'Manrope_400Regular',
    fontSize: 13,
  },
  heroIdentityText: {
    gap: 6,
  },
  heroChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    paddingTop: 6,
  },
  heroChip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(171, 30, 36, 0.12)',
    backgroundColor: '#fff4f1',
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  heroChipText: {
    color: '#8b3238',
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
  },
  avatarFrame: {
    width: 112,
    height: 112,
    borderRadius: 34,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f1dfd5',
    borderWidth: 1,
    borderColor: 'rgba(171, 30, 36, 0.12)',
  },
  profileAvatarImage: {
    width: '100%',
    height: '100%',
  },
  profileAvatarFallback: {
    color: '#ab1e24',
    fontFamily: 'Manrope_700Bold',
    fontSize: 34,
  },
  overviewGrid: {
    gap: 10,
  },
  overviewGridWide: {
    flex: 0.95,
    justifyContent: 'space-between',
  },
  overviewCard: {
    borderRadius: 22,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderWidth: 1,
    borderColor: 'rgba(142, 34, 40, 0.1)',
    backgroundColor: '#ffffff',
    padding: 14,
  },
  overviewIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f8ece6',
  },
  overviewLabel: {
    flex: 1,
    color: '#8d5a5f',
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
  },
  overviewValue: {
    color: '#5f1c21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 13,
    flexShrink: 1,
  },
  contentLayout: {
    gap: 18,
  },
  contentLayoutWide: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  primaryColumn: {
    gap: 18,
  },
  primaryColumnWide: {
    flex: 0.95,
    minWidth: 300,
  },
  secondaryColumn: {
    gap: 18,
  },
  secondaryColumnWide: {
    flex: 1.05,
    minWidth: 340,
  },
  panel: {
    borderRadius: 28,
    borderWidth: 1,
    borderColor: 'rgba(142, 34, 40, 0.12)',
    backgroundColor: 'rgba(255, 251, 247, 0.94)',
    padding: 20,
    gap: 16,
  },
  panelHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 14,
  },
  panelTitleWrap: {
    flex: 1,
    gap: 4,
  },
  panelEyebrow: {
    color: '#8d5a5f',
    fontFamily: 'Manrope_700Bold',
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  panelTitle: {
    color: '#5f1c21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 20,
    lineHeight: 26,
  },
  panelDescription: {
    color: '#8d5a5f',
    fontFamily: 'Manrope_400Regular',
    fontSize: 14,
    lineHeight: 20,
  },
  panelIconBadge: {
    width: 40,
    height: 40,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f8ece6',
  },
  nameEditorBlock: {
    gap: 10,
  },
  nameInput: {
    borderWidth: 1,
    borderColor: 'rgba(171, 30, 36, 0.12)',
    borderRadius: 18,
    backgroundColor: '#ffffff',
    color: '#5f1c21',
    fontFamily: 'Manrope_400Regular',
    fontSize: 15,
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  primaryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderWidth: 1,
    borderColor: '#ab1e24',
    backgroundColor: '#ab1e24',
    borderRadius: 18,
    paddingVertical: 14,
  },
  primaryButtonText: {
    color: '#ffffff',
    fontFamily: 'Manrope_700Bold',
    fontSize: 14,
  },
  secondaryButton: {
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(171, 30, 36, 0.14)',
    backgroundColor: '#fff3ef',
    borderRadius: 18,
    paddingVertical: 14,
  },
  secondaryButtonText: {
    color: '#ab1e24',
    fontFamily: 'Manrope_700Bold',
    fontSize: 14,
  },
  infoNotice: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(171, 30, 36, 0.1)',
    backgroundColor: '#ffffff',
    padding: 14,
    gap: 6,
  },
  infoNoticeTitle: {
    color: '#8d5a5f',
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  infoNoticeBody: {
    color: '#5f1c21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 16,
  },
  infoNoticeHint: {
    color: '#8d5a5f',
    fontFamily: 'Manrope_400Regular',
    fontSize: 13,
    lineHeight: 18,
  },
  detailList: {
    gap: 12,
  },
  detailRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(142, 34, 40, 0.08)',
    backgroundColor: '#ffffff',
    padding: 14,
  },
  detailIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f8ece6',
  },
  detailTextWrap: {
    flex: 1,
    gap: 4,
  },
  detailLabel: {
    color: '#8d5a5f',
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
  },
  detailValue: {
    color: '#5f1c21',
    fontFamily: 'Manrope_400Regular',
    fontSize: 14,
    lineHeight: 19,
  },
  accessChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  accessChip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(171, 30, 36, 0.12)',
    backgroundColor: '#fff4f1',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  accessChipText: {
    color: '#8b3238',
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
  },
  emptyState: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(142, 34, 40, 0.08)',
    backgroundColor: '#ffffff',
    padding: 18,
    alignItems: 'center',
  },
  emptyStateText: {
    color: '#8d5a5f',
    fontFamily: 'Manrope_700Bold',
    fontSize: 14,
  },
  error: {
    color: '#b42318',
    fontFamily: 'Manrope_700Bold',
    fontSize: 13,
  },
  buttonDisabled: {
    opacity: 0.65,
  },
});
