import { StyleSheet } from 'react-native';

const BORDER = 'rgba(171, 30, 36, 0.12)';
const SOFT_BORDER = 'rgba(171, 30, 36, 0.08)';
const CARD = '#fffdfb';
const PANEL = '#ffffff';
const BRAND = '#ab1e24';
const BRAND_SOFT = '#fff3ef';
const TEXT = '#5f1c21';
const MUTED = '#8d5a5f';

export const styles = StyleSheet.create({
  pageRoot: {
    flex: 1,
  },
  pageScroll: {
    flex: 1,
  },
  pageContent: {
    gap: 18,
    paddingBottom: 24,
  },
  heroCard: {
    borderRadius: 28,
    borderWidth: 1,
    borderColor: BORDER,
    backgroundColor: CARD,
    padding: 20,
    gap: 16,
  },
  heroHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 14,
    flexWrap: 'wrap',
  },
  heroCopy: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  title: {
    color: TEXT,
    fontFamily: 'Manrope_700Bold',
    fontSize: 28,
    lineHeight: 34,
  },
  subtitle: {
    color: MUTED,
    fontFamily: 'Manrope_400Regular',
    fontSize: 13,
    lineHeight: 19,
  },
  heroBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: SOFT_BORDER,
    backgroundColor: BRAND_SOFT,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  heroBadgeText: {
    color: BRAND,
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
  },
  heroStatsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  heroStatCard: {
    minWidth: 140,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: SOFT_BORDER,
    backgroundColor: PANEL,
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 3,
  },
  heroStatValue: {
    color: TEXT,
    fontFamily: 'Manrope_700Bold',
    fontSize: 24,
    lineHeight: 28,
  },
  heroStatLabel: {
    color: MUTED,
    fontFamily: 'Manrope_700Bold',
    fontSize: 11,
  },
  mainGrid: {
    gap: 18,
  },
  mainGridWide: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  sidebarColumn: {
    gap: 18,
  },
  sidebarColumnWide: {
    width: 340,
    flexShrink: 0,
  },
  contentColumn: {
    flex: 1,
    minWidth: 0,
  },
  surfaceCard: {
    borderRadius: 26,
    borderWidth: 1,
    borderColor: BORDER,
    backgroundColor: CARD,
    padding: 18,
    gap: 16,
  },
  surfaceHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  surfaceHeaderCopy: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  surfaceEyebrow: {
    color: MUTED,
    fontFamily: 'Manrope_700Bold',
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  surfaceTitle: {
    color: TEXT,
    fontFamily: 'Manrope_700Bold',
    fontSize: 20,
    lineHeight: 26,
  },
  surfaceSubtitle: {
    color: MUTED,
    fontFamily: 'Manrope_400Regular',
    fontSize: 12,
    lineHeight: 18,
  },
  surfaceCountPill: {
    minWidth: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 999,
    borderWidth: 1,
    borderColor: SOFT_BORDER,
    backgroundColor: BRAND_SOFT,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  surfaceCountText: {
    color: BRAND,
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
  },
  selectTrigger: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: SOFT_BORDER,
    backgroundColor: PANEL,
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  selectTriggerCopy: {
    flex: 1,
    gap: 3,
  },
  selectTriggerLabel: {
    color: MUTED,
    fontFamily: 'Manrope_700Bold',
    fontSize: 11,
  },
  selectTriggerText: {
    color: TEXT,
    fontFamily: 'Manrope_700Bold',
    fontSize: 14,
  },
  selectList: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: SOFT_BORDER,
    backgroundColor: PANEL,
    overflow: 'hidden',
  },
  selectItem: {
    paddingHorizontal: 14,
    paddingVertical: 11,
    borderBottomWidth: 1,
    borderBottomColor: SOFT_BORDER,
  },
  selectItemActive: {
    backgroundColor: BRAND_SOFT,
  },
  selectItemText: {
    color: TEXT,
    fontFamily: 'Manrope_700Bold',
    fontSize: 13,
  },
  selectItemTextActive: {
    color: BRAND,
  },
  addressCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: SOFT_BORDER,
    backgroundColor: '#fff8f5',
    padding: 14,
  },
  addressIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: SOFT_BORDER,
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  addressCopy: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  addressLabel: {
    color: MUTED,
    fontFamily: 'Manrope_700Bold',
    fontSize: 11,
  },
  addressText: {
    color: TEXT,
    fontFamily: 'Manrope_400Regular',
    fontSize: 13,
    lineHeight: 19,
  },
  successCard: {
    borderRadius: 26,
    borderWidth: 1,
    borderColor: BORDER,
    backgroundColor: CARD,
    padding: 18,
    gap: 14,
  },
  successHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  successIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: SOFT_BORDER,
    backgroundColor: BRAND_SOFT,
    alignItems: 'center',
    justifyContent: 'center',
  },
  successCopy: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  successTitle: {
    color: TEXT,
    fontFamily: 'Manrope_700Bold',
    fontSize: 18,
  },
  successMeta: {
    color: MUTED,
    fontFamily: 'Manrope_400Regular',
    fontSize: 12,
    lineHeight: 17,
  },
  summaryCard: {
    borderRadius: 26,
    borderWidth: 1,
    borderColor: BORDER,
    backgroundColor: CARD,
    padding: 18,
    gap: 14,
  },
  summaryTitle: {
    color: TEXT,
    fontFamily: 'Manrope_700Bold',
    fontSize: 18,
  },
  summaryMetricRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  summaryMetricLabel: {
    color: MUTED,
    fontFamily: 'Manrope_400Regular',
    fontSize: 13,
  },
  summaryMetricValue: {
    color: TEXT,
    fontFamily: 'Manrope_700Bold',
    fontSize: 15,
  },
  listBlock: {
    gap: 12,
  },
  productGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  productGridItem: {
    width: '48.8%',
  },
  productGridItemSmall: {
    width: '100%',
  },
  productCard: {
    borderRadius: 22,
    borderWidth: 1,
    borderColor: SOFT_BORDER,
    backgroundColor: PANEL,
    padding: 14,
  },
  productInfoRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 14,
  },
  productInfoRowSmall: {
    flexDirection: 'column',
    alignItems: 'stretch',
  },
  productInfoColumn: {
    flex: 1,
    minWidth: 0,
    gap: 6,
  },
  productInfoColumnSmall: {
    width: '100%',
  },
  productImageFrame: {
    width: 118,
    height: 118,
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: '#f3dcdd',
  },
  productImageFrameSmall: {
    width: '100%',
    height: 190,
  },
  productImagePlaceholder: {
    width: 118,
    height: 118,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: SOFT_BORDER,
    backgroundColor: '#fff7f4',
    alignItems: 'center',
    justifyContent: 'center',
  },
  productImageThumb: {
    width: '100%',
    height: '100%',
  },
  productTitle: {
    color: TEXT,
    fontFamily: 'Manrope_700Bold',
    fontSize: 16,
    lineHeight: 22,
  },
  docItemMeta: {
    color: MUTED,
    fontFamily: 'Manrope_400Regular',
    fontSize: 12,
    lineHeight: 17,
  },
  lineTotalText: {
    color: BRAND,
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
    lineHeight: 17,
  },
  error: {
    color: '#b42318',
    fontFamily: 'Manrope_700Bold',
    fontSize: 13,
    lineHeight: 18,
  },
  primaryButton: {
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#97161c',
    backgroundColor: BRAND,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  secondaryButton: {
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: SOFT_BORDER,
    backgroundColor: PANEL,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  primaryButtonText: {
    color: '#ffffff',
    fontFamily: 'Manrope_700Bold',
    fontSize: 13,
  },
  secondaryButtonText: {
    color: '#7f1b21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 13,
  },
});
