import { Platform, StyleSheet } from 'react-native';

const BORDER = 'rgba(171, 30, 36, 0.18)';
const SOFT_BORDER = 'rgba(171, 30, 36, 0.14)';
const CARD = '#fffdfb';
const PANEL = '#ffffff';
const BRAND = '#ab1e24';
const BRAND_SOFT = '#fff3ef';
const TEXT = '#5f1c21';
const MUTED = '#8d5a5f';
const WEB_INPUT_RESET = Platform.select({
  web: {
    outlineStyle: 'none',
    outlineWidth: 0,
    outlineColor: 'transparent',
    boxShadow: 'none',
    appearance: 'none',
    WebkitAppearance: 'none',
  } as never,
  default: {},
});

export const styles = StyleSheet.create({
  pageRoot: {
    flex: 1,
    position: 'relative',
  },
  pageScroll: {
    flex: 1,
  },
  pageContent: {
    gap: 18,
    paddingBottom: 24,
  },
  pageContentWithMobileSummary: {
    gap: 10,
    paddingBottom: 112,
  },
  heroCard: {
    borderRadius: 28,
    borderWidth: 1,
    borderColor: BORDER,
    backgroundColor: CARD,
    padding: 20,
    gap: 16,
  },
  mobileHeroCard: {
    borderRadius: 18,
    padding: 12,
    gap: 8,
  },
  heroHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 14,
    flexWrap: 'wrap',
  },
  heroCopy: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  title: {
    color: TEXT,
    fontFamily: 'Manrope_700Bold',
    fontSize: 28,
    lineHeight: 34,
  },
  mobileTitle: {
    fontSize: 22,
    lineHeight: 27,
  },
  subtitle: {
    color: MUTED,
    fontFamily: 'Manrope_400Regular',
    fontSize: 13,
    lineHeight: 19,
  },
  mobileSubtitle: {
    fontSize: 12,
    lineHeight: 17,
  },
  heroBadge: {
    maxWidth: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: SOFT_BORDER,
    backgroundColor: BRAND_SOFT,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  heroBadgeText: {
    color: BRAND,
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
  },
  heroStatsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  heroStatCard: {
    minWidth: 140,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: SOFT_BORDER,
    backgroundColor: PANEL,
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 3,
  },
  heroStatValue: {
    color: TEXT,
    fontFamily: 'Manrope_700Bold',
    fontSize: 24,
    lineHeight: 28,
  },
  heroStatLabel: {
    color: MUTED,
    fontFamily: 'Manrope_700Bold',
    fontSize: 11,
  },
  mainGrid: {
    gap: 18,
  },
  mainGridWide: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  sidebarColumn: {
    gap: 18,
  },
  sidebarColumnWide: {
    width: 340,
    flexShrink: 0,
  },
  contentColumn: {
    flex: 1,
    minWidth: 0,
    gap: 18,
  },
  mobileContentStack: {
    gap: 10,
  },
  surfaceCard: {
    borderRadius: 26,
    borderWidth: 1,
    borderColor: BORDER,
    backgroundColor: CARD,
    padding: 18,
    gap: 16,
  },
  mobileSurfaceCard: {
    borderRadius: 18,
    padding: 12,
    gap: 10,
  },
  mobileFilterPanel: {
    borderRadius: 18,
    padding: 12,
    gap: 10,
  },
  surfaceHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  surfaceHeaderCopy: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  surfaceEyebrow: {
    color: MUTED,
    fontFamily: 'Manrope_700Bold',
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  surfaceTitle: {
    color: TEXT,
    fontFamily: 'Manrope_700Bold',
    fontSize: 20,
    lineHeight: 26,
  },
  surfaceSubtitle: {
    color: MUTED,
    fontFamily: 'Manrope_400Regular',
    fontSize: 12,
    lineHeight: 18,
  },
  orderNoticeBox: {
    alignSelf: 'flex-start',
    maxWidth: '100%',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: SOFT_BORDER,
    backgroundColor: '#fff7f4',
    paddingHorizontal: 12,
    paddingVertical: 9,
    gap: 3,
  },
  orderNoticeLabel: {
    color: BRAND,
    fontFamily: 'Manrope_700Bold',
    fontSize: 11,
    lineHeight: 15,
  },
  orderNoticeText: {
    color: MUTED,
    fontFamily: 'Manrope_400Regular',
    fontSize: 12,
    lineHeight: 18,
  },
  mobileOrderNoticeBox: {
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  surfaceCountPill: {
    minWidth: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 999,
    borderWidth: 1,
    borderColor: SOFT_BORDER,
    backgroundColor: BRAND_SOFT,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  surfaceCountText: {
    color: BRAND,
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
  },
  supplierDropdownOptionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  mobileChipScrollerContent: {
    gap: 8,
    paddingRight: 4,
  },
  supplierDropdownWrap: {
    gap: 8,
  },
  supplierDropdownButton: {
    minHeight: 56,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: SOFT_BORDER,
    backgroundColor: '#ffffff',
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  mobileSupplierDropdownButton: {
    minHeight: 50,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  supplierDropdownButtonActive: {
    borderColor: BRAND,
    backgroundColor: BRAND_SOFT,
  },
  supplierDropdownButtonTextBlock: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  supplierDropdownLabel: {
    color: MUTED,
    fontFamily: 'Manrope_700Bold',
    fontSize: 10,
    lineHeight: 14,
    textTransform: 'uppercase',
  },
  supplierDropdownValue: {
    color: TEXT,
    fontFamily: 'Manrope_700Bold',
    fontSize: 15,
    lineHeight: 20,
  },
  supplierDropdownMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  supplierDropdownCount: {
    color: BRAND,
    fontFamily: 'Manrope_700Bold',
    fontSize: 14,
    lineHeight: 18,
  },
  supplierDropdownMenu: {
    maxHeight: 280,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: SOFT_BORDER,
    backgroundColor: '#ffffff',
    overflow: 'hidden',
  },
  supplierDropdownOption: {
    minHeight: 44,
    justifyContent: 'center',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(171, 30, 36, 0.08)',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  supplierDropdownOptionActive: {
    backgroundColor: BRAND_SOFT,
  },
  supplierDropdownOptionText: {
    flex: 1,
    color: TEXT,
    fontFamily: 'Manrope_700Bold',
    fontSize: 13,
  },
  supplierDropdownOptionTextActive: {
    color: BRAND,
  },
  supplierDropdownOptionCount: {
    color: TEXT,
    fontFamily: 'Manrope_700Bold',
    fontSize: 13,
  },
  supplierDropdownOptionCountActive: {
    color: BRAND,
  },
  searchWrap: {
    gap: 8,
  },
  searchShell: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: SOFT_BORDER,
    backgroundColor: '#ffffff',
    paddingHorizontal: 12,
  },
  searchInput: {
    ...WEB_INPUT_RESET,
    flex: 1,
    minWidth: 0,
    color: TEXT,
    fontFamily: 'Manrope_400Regular',
    fontSize: 14,
    paddingVertical: 12,
  },
  categoryWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  categoryChip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: SOFT_BORDER,
    backgroundColor: '#ffffff',
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  mobileCategoryChip: {
    minHeight: 44,
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  categoryChipActive: {
    borderColor: BRAND,
    backgroundColor: BRAND_SOFT,
  },
  categoryChipText: {
    color: '#7f1b21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
  },
  categoryChipTextActive: {
    color: BRAND,
  },
  summaryCard: {
    borderRadius: 26,
    borderWidth: 1,
    borderColor: BORDER,
    backgroundColor: CARD,
    padding: 18,
    gap: 14,
  },
  summaryBottomWrap: {
    width: '100%',
  },
  summaryTitle: {
    color: TEXT,
    fontFamily: 'Manrope_700Bold',
    fontSize: 18,
  },
  summaryMetricRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  summaryMetricLabel: {
    color: MUTED,
    fontFamily: 'Manrope_400Regular',
    fontSize: 13,
  },
  summaryMetricValue: {
    color: TEXT,
    fontFamily: 'Manrope_700Bold',
    fontSize: 15,
  },
  productGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  tabletCompactProductGrid: {
    gap: 10,
  },
  mobileProductGrid: {
    flexDirection: 'column',
    flexWrap: 'nowrap',
    gap: 8,
  },
  listBlock: {
    gap: 12,
  },
  productGridItem: {
    width: '48.8%',
  },
  productGridItemSmall: {
    width: '100%',
  },
  productCard: {
    borderRadius: 22,
    borderWidth: 1,
    borderColor: SOFT_BORDER,
    backgroundColor: PANEL,
    padding: 14,
    gap: 12,
  },
  mobileProductCard: {
    width: '100%',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: SOFT_BORDER,
    backgroundColor: PANEL,
    padding: 10,
    gap: 8,
  },
  tabletProductCard: {
    width: '48.8%',
  },
  productCardHeader: {
    gap: 8,
  },
  productBadgeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  productBadge: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: SOFT_BORDER,
    backgroundColor: BRAND_SOFT,
    paddingHorizontal: 9,
    paddingVertical: 5,
  },
  productBadgeText: {
    color: BRAND,
    fontFamily: 'Manrope_700Bold',
    fontSize: 10,
  },
  productInfoRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 14,
  },
  productInfoRowSmall: {
    flexDirection: 'column',
    alignItems: 'stretch',
  },
  productInfoColumn: {
    flex: 1,
    minWidth: 0,
    gap: 10,
  },
  productInfoColumnSmall: {
    width: '100%',
  },
  mobileProductHeaderRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  mobileProductTitleColumn: {
    flex: 1,
    minWidth: 0,
    gap: 6,
  },
  mobileProductNameRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    flexWrap: 'wrap',
    gap: 6,
  },
  mobileCartonReferenceBlock: {
    gap: 1,
  },
  mobileCartonReferenceLabel: {
    color: MUTED,
    fontFamily: 'Manrope_700Bold',
    fontSize: 10,
    lineHeight: 14,
  },
  mobileCartonReferenceText: {
    color: TEXT,
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
    lineHeight: 16,
  },
  productTitleBlock: {
    gap: 6,
  },
  productImageFrame: {
    width: 118,
    height: 118,
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: '#f3dcdd',
  },
  productImageFrameSmall: {
    width: '100%',
    height: 190,
  },
  mobileProductImageFrame: {
    width: 68,
    height: 68,
    borderRadius: 12,
    flexShrink: 0,
  },
  productImagePlaceholder: {
    width: 118,
    height: 118,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: SOFT_BORDER,
    backgroundColor: '#fff7f4',
    alignItems: 'center',
    justifyContent: 'center',
  },
  productImageThumb: {
    width: '100%',
    height: '100%',
  },
  productTitle: {
    color: TEXT,
    fontFamily: 'Manrope_700Bold',
    fontSize: 18,
    lineHeight: 24,
  },
  mobileProductTitle: {
    flexShrink: 1,
    minWidth: 0,
    color: TEXT,
    fontFamily: 'Manrope_700Bold',
    fontSize: 15,
    lineHeight: 20,
  },
  productSpecificationList: {
    gap: 3,
  },
  productSpecificationText: {
    color: BRAND,
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
    lineHeight: 16,
  },
  specificationList: {
    gap: 12,
  },
  mobileSpecificationList: {
    gap: 6,
  },
  specificationCard: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: SOFT_BORDER,
    backgroundColor: '#fffaf7',
    padding: 14,
    gap: 12,
  },
  specificationCardActive: {
    borderColor: BRAND,
    backgroundColor: '#fff4ef',
  },
  mobileSpecificationRow: {
    minHeight: 50,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(171, 30, 36, 0.12)',
    backgroundColor: '#fffaf7',
    paddingLeft: 10,
    paddingRight: 6,
    paddingVertical: 5,
  },
  mobileSpecificationCopy: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  mobileSpecificationTitle: {
    color: TEXT,
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
    lineHeight: 16,
  },
  mobileSpecificationMeta: {
    color: MUTED,
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
    lineHeight: 16,
  },
  specificationMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  specificationMetaItem: {
    flex: 1,
    minWidth: 110,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(171, 30, 36, 0.1)',
    backgroundColor: '#ffffff',
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 2,
  },
  specificationMetaLabel: {
    color: MUTED,
    fontFamily: 'Manrope_700Bold',
    fontSize: 10,
    lineHeight: 14,
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  specificationMetaValue: {
    color: TEXT,
    fontFamily: 'Manrope_700Bold',
    fontSize: 13,
    lineHeight: 18,
  },
  specificationPriceValue: {
    color: BRAND,
  },
  quantitySection: {
    gap: 8,
  },
  quantityLabel: {
    color: MUTED,
    fontFamily: 'Manrope_700Bold',
    fontSize: 10,
    lineHeight: 14,
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  quantityBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  quantityInputWrap: {
    width: 110,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(171, 30, 36, 0.16)',
    backgroundColor: '#ffffff',
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 42,
  },
  quantityInput: {
    ...WEB_INPUT_RESET,
    width: '100%',
    color: TEXT,
    fontFamily: 'Manrope_700Bold',
    fontSize: 18,
    lineHeight: 20,
    paddingVertical: 0,
  },
  quantityUnitText: {
    color: MUTED,
    fontFamily: 'Manrope_700Bold',
    fontSize: 13,
    lineHeight: 18,
  },
  mobileQuantityStepper: {
    flexDirection: 'row',
    alignItems: 'center',
    flexShrink: 0,
    gap: 4,
  },
  mobileQuantityButton: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(171, 30, 36, 0.16)',
    backgroundColor: '#ffffff',
  },
  mobileQuantityButtonText: {
    color: BRAND,
    fontFamily: 'Manrope_700Bold',
    fontSize: 18,
    lineHeight: 22,
  },
  mobileQuantityInputWrap: {
    width: 48,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(171, 30, 36, 0.16)',
    backgroundColor: '#ffffff',
  },
  mobileQuantityInput: {
    ...WEB_INPUT_RESET,
    width: '100%',
    height: '100%',
    color: TEXT,
    fontFamily: 'Manrope_700Bold',
    fontSize: 15,
    lineHeight: 44,
    paddingVertical: 0,
    paddingHorizontal: 0,
    textAlign: 'center',
    textAlignVertical: 'center',
  },
  emptyCard: {
    width: '100%',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: SOFT_BORDER,
    backgroundColor: '#fff8f5',
    paddingHorizontal: 14,
    paddingVertical: 16,
  },
  docEmpty: {
    color: MUTED,
    fontFamily: 'Manrope_400Regular',
    fontSize: 13,
    lineHeight: 19,
  },
  error: {
    color: '#b42318',
    fontFamily: 'Manrope_700Bold',
    fontSize: 13,
    lineHeight: 18,
  },
  primaryButton: {
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#97161c',
    backgroundColor: BRAND,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  primaryButtonText: {
    color: '#ffffff',
    fontFamily: 'Manrope_700Bold',
    fontSize: 13,
  },
  mobileSummaryBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 20,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderTopWidth: 1,
    borderTopColor: BORDER,
    backgroundColor: '#fffdfb',
    paddingHorizontal: 12,
    paddingTop: 10,
    paddingBottom: 14,
    ...Platform.select({
      web: {
        boxShadow: '0 -12px 28px rgba(95, 28, 33, 0.12)',
      } as never,
      default: {
        shadowColor: '#5f1c21',
        shadowOpacity: 0.12,
        shadowRadius: 14,
        shadowOffset: { width: 0, height: -6 },
        elevation: 8,
      },
    }),
  },
  mobileSummaryMetrics: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    gap: 8,
  },
  mobileSummaryMetric: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  mobileSummaryLabel: {
    color: MUTED,
    fontFamily: 'Manrope_700Bold',
    fontSize: 10,
    lineHeight: 14,
  },
  mobileSummaryValue: {
    color: TEXT,
    fontFamily: 'Manrope_700Bold',
    fontSize: 15,
    lineHeight: 19,
  },
  mobileSummaryButton: {
    minWidth: 118,
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#97161c',
    backgroundColor: BRAND,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
});
