import { StyleSheet } from 'react-native';

const CARD_BORDER = 'rgba(171, 30, 36, 0.18)';
const CARD_BORDER_SOFT = 'rgba(171, 30, 36, 0.14)';

export const styles = StyleSheet.create({
  panelStack: {
    gap: 18,
  },
  panelHeader: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: CARD_BORDER,
    backgroundColor: '#fffdfb',
    padding: 18,
    gap: 14,
  },
  panelHeaderCompact: {
    padding: 14,
  },
  panelHeaderCopy: {
    gap: 4,
  },
  panelTitle: {
    color: '#5f1c21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 20,
  },
  panelSubtitle: {
    color: '#8d5a5f',
    fontFamily: 'Manrope_400Regular',
    fontSize: 13,
    lineHeight: 18,
  },
  panelStatsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  panelStatCard: {
    minWidth: 120,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: CARD_BORDER_SOFT,
    backgroundColor: '#ffffff',
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 2,
  },
  panelStatCardCompact: {
    flex: 1,
    minWidth: 0,
  },
  panelStatValue: {
    color: '#5f1c21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 17,
  },
  panelStatLabel: {
    color: '#8d5a5f',
    fontFamily: 'Manrope_700Bold',
    fontSize: 11,
  },
  panelGrid: {
    gap: 18,
  },
  panelGridWide: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  surfaceCard: {
    flex: 1,
    minWidth: 0,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: CARD_BORDER,
    backgroundColor: '#fffdfb',
    padding: 18,
    gap: 14,
  },
  surfaceCardCompact: {
    padding: 14,
  },
  surfaceHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  surfaceHeaderCompact: {
    flexDirection: 'column',
  },
  surfaceHeaderCopy: {
    flex: 1,
    gap: 3,
  },
  surfaceEyebrow: {
    color: '#8d5a5f',
    fontFamily: 'Manrope_700Bold',
    fontSize: 11,
  },
  surfaceTitle: {
    color: '#5f1c21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 18,
  },
  surfaceSubtitle: {
    color: '#8d5a5f',
    fontFamily: 'Manrope_400Regular',
    fontSize: 12,
    lineHeight: 17,
  },
  surfaceCounterPill: {
    color: '#8d5a5f',
    fontFamily: 'Manrope_700Bold',
    fontSize: 11,
    backgroundColor: '#fff4ef',
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(171, 30, 36, 0.08)',
    paddingHorizontal: 9,
    paddingVertical: 5,
  },
  surfaceCounterPillCompact: {
    alignSelf: 'flex-start',
  },
  helperText: {
    color: '#8d5a5f',
    fontFamily: 'Manrope_400Regular',
    fontSize: 12,
  },
  error: {
    color: '#b42318',
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
  },
  levelChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  levelChip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(171, 30, 36, 0.1)',
    backgroundColor: '#ffffff',
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  levelChipCompact: {
    flexBasis: '48%',
    flexGrow: 1,
    minWidth: 0,
  },
  levelChipActive: {
    borderColor: '#ab1e24',
    backgroundColor: '#fff1ef',
  },
  levelChipText: {
    color: '#8d5458',
    fontFamily: 'Manrope_700Bold',
    fontSize: 11,
  },
  levelChipTextCompact: {
    textAlign: 'center',
  },
  levelChipTextActive: {
    color: '#ab1e24',
  },
  levelList: {
    gap: 8,
  },
  levelSelectTrigger: {
    minHeight: 52,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(171, 30, 36, 0.1)',
    backgroundColor: '#ffffff',
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  levelSelectTriggerActive: {
    borderColor: '#ab1e24',
    backgroundColor: '#fff8f5',
  },
  levelSelectTriggerCopy: {
    flex: 1,
    minWidth: 0,
    gap: 3,
  },
  levelSelectTriggerLabel: {
    color: '#8d5a5f',
    fontFamily: 'Manrope_700Bold',
    fontSize: 10,
  },
  levelSelectTriggerValue: {
    color: '#5f1c21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 13,
    lineHeight: 18,
  },
  levelListItem: {
    minHeight: 48,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(171, 30, 36, 0.1)',
    backgroundColor: '#ffffff',
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  levelListItemActive: {
    borderColor: '#ab1e24',
    backgroundColor: '#fff1ef',
  },
  levelListItemCopy: {
    flex: 1,
    minWidth: 0,
  },
  levelListItemText: {
    color: '#8d5458',
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
    lineHeight: 18,
  },
  levelListItemTextActive: {
    color: '#ab1e24',
  },
  actionRail: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  actionRailCompact: {
    flexDirection: 'column',
  },
  actionButton: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(171, 30, 36, 0.1)',
    backgroundColor: '#fff8f5',
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  actionButtonCompact: {
    width: '100%',
    alignItems: 'center',
  },
  actionButtonText: {
    color: '#7f1b21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 11,
  },
  scenarioStack: {
    gap: 10,
  },
  scenarioCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: CARD_BORDER_SOFT,
    backgroundColor: '#ffffff',
    padding: 12,
    gap: 10,
  },
  scenarioHeaderRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 10,
  },
  scenarioToggleButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  scenarioHeaderCopy: {
    flex: 1,
    gap: 2,
  },
  scenarioTitle: {
    color: '#7a2328',
    fontFamily: 'Manrope_700Bold',
    fontSize: 13,
  },
  scenarioMeta: {
    color: '#996165',
    fontFamily: 'Manrope_400Regular',
    fontSize: 11,
  },
  scenarioCollapsedHint: {
    color: '#996165',
    fontFamily: 'Manrope_400Regular',
    fontSize: 11,
    lineHeight: 16,
  },
  scenarioActionsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    justifyContent: 'flex-end',
  },
  scenarioActionsRowCompact: {
    flexDirection: 'column',
  },
  scenarioActionButton: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(171, 30, 36, 0.1)',
    backgroundColor: '#fff5f3',
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  scenarioActionButtonCompact: {
    width: '100%',
    alignItems: 'center',
  },
  scenarioActionButtonText: {
    color: '#7f1b21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 10,
  },
  sectionChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  sectionChip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(171, 30, 36, 0.1)',
    backgroundColor: '#fffdfb',
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  sectionChipDense: {
    flexBasis: '48%',
    flexGrow: 1,
    minWidth: 0,
  },
  sectionChipCompact: {
    width: '100%',
    minWidth: 0,
  },
  sectionChipActive: {
    borderColor: '#ab1e24',
    backgroundColor: '#fff1ef',
  },
  sectionChipText: {
    color: '#8d5458',
    fontFamily: 'Manrope_700Bold',
    fontSize: 11,
  },
  sectionChipTextCompact: {
    textAlign: 'center',
  },
  sectionChipTextActive: {
    color: '#ab1e24',
  },
  quizScenarioStack: {
    gap: 10,
  },
  quizScenarioCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: CARD_BORDER_SOFT,
    backgroundColor: '#ffffff',
    padding: 12,
    gap: 10,
  },
  quizSectionStack: {
    gap: 8,
  },
  quizSectionCard: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: CARD_BORDER_SOFT,
    backgroundColor: '#fffaf8',
    padding: 10,
    gap: 8,
  },
  quizSectionTitle: {
    color: '#7a2328',
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
  },
  quizLinkRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  quizLinkRowCompact: {
    flexWrap: 'wrap',
    alignItems: 'stretch',
  },
  quizLanguageBadge: {
    minWidth: 46,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(171, 30, 36, 0.1)',
    backgroundColor: '#fff3ef',
    color: '#7f1b21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 11,
    textAlign: 'center',
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  quizLanguageBadgeCompact: {
    minWidth: 0,
    width: '100%',
  },
  quizLinkInput: {
    flex: 1,
    minWidth: 0,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(171, 30, 36, 0.12)',
    backgroundColor: '#ffffff',
    color: '#7a181d',
    fontFamily: 'Manrope_400Regular',
    fontSize: 12,
    paddingHorizontal: 10,
    paddingVertical: 9,
  },
  quizLinkInputCompact: {
    width: '100%',
  },
  quizLinkSaveButton: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(171, 30, 36, 0.12)',
    backgroundColor: '#fff8f5',
    paddingHorizontal: 10,
    paddingVertical: 9,
  },
  quizLinkSaveButtonCompact: {
    width: '100%',
    alignItems: 'center',
  },
  quizLinkSaveButtonText: {
    color: '#7f1b21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 11,
  },
  primaryButton: {
    borderRadius: 18,
    paddingVertical: 14,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#97161c',
    backgroundColor: '#ab1e24',
    marginTop: 4,
  },
  buttonDisabled: {
    opacity: 0.65,
  },
  primaryButtonText: {
    color: '#ffffff',
    fontFamily: 'Manrope_700Bold',
    fontSize: 14,
  },
});
