import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  card: {
    backgroundColor: 'rgba(255,255,255,0.92)',
    borderRadius: 22,
    padding: 18,
    borderWidth: 1,
    borderColor: '#e8c3c4',
    gap: 12,
  },
  stackCardWrap: {
    gap: 14,
  },
  managerDashboardLayout: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 14,
    flexWrap: 'wrap',
  },
  managerLeftCard: {
    flexBasis: 320,
    flexGrow: 1,
    minWidth: 280,
  },
  managerLeftColumn: {
    flexBasis: 320,
    flexGrow: 1,
    minWidth: 280,
    gap: 12,
  },
  employeeNewsSpacing: {
    marginTop: 10,
  },
  quickColumn: {
    flexBasis: 420,
    flexGrow: 1,
    minWidth: 300,
    gap: 12,
  },
  quickBlock: {
    backgroundColor: 'rgba(255,255,255,0.92)',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#e8c3c4',
    padding: 14,
    gap: 10,
  },
  whatsNewHighlightBlock: {
    borderColor: '#cc6268',
    borderWidth: 2,
    backgroundColor: '#fff6f6',
    shadowColor: '#b7464d',
    shadowOpacity: 0.18,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 4,
  },
  whatsNewHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  whatsNewHeaderMain: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
  },
  whatsNewHeaderIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ab1e24',
  },
  whatsNewHeaderTitleWrap: {
    flex: 1,
    gap: 2,
  },
  whatsNewKicker: {
    color: '#ab1e24',
    fontFamily: 'Manrope_700Bold',
    fontSize: 11,
    letterSpacing: 0.4,
  },
  whatsNewStatusPill: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#d97f84',
    backgroundColor: '#ffe9eb',
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  whatsNewStatusPillText: {
    color: '#9e1f25',
    fontFamily: 'Manrope_700Bold',
    fontSize: 10,
  },
  quickBlockTitle: {
    color: '#7f1b21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 15,
  },
  quickSearchInput: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#dfb0b2',
    backgroundColor: '#ffffff',
    color: '#7a181d',
    fontFamily: 'Manrope_400Regular',
    fontSize: 16,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  whatsNewMessageInput: {
    minHeight: 120,
  },
  quickRowCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#efd8d9',
    backgroundColor: '#fff9f9',
    padding: 10,
    gap: 6,
  },
  quickLevelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  quickLevelInfo: {
    flex: 1,
    gap: 4,
  },
  quickRowTitle: {
    color: '#7f1b21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 13,
  },
  quickSectionDivider: {
    marginTop: 4,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#ead0d2',
  },
  quickSectionTitle: {
    color: '#7f1b21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 13,
  },
  quickNewsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  newsFeedHighlightBlock: {
    borderColor: '#5f8d43',
    borderWidth: 2,
    backgroundColor: '#f8fff4',
    shadowColor: '#5f8d43',
    shadowOpacity: 0.16,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 3,
  },
  newsFeedIntroStrip: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#c7dfb8',
    backgroundColor: '#eef9e7',
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  newsFeedTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
  },
  newsFeedIconWrap: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#6f9b50',
  },
  newsFeedKicker: {
    color: '#4f7c35',
    fontFamily: 'Manrope_700Bold',
    fontSize: 10,
    letterSpacing: 0.4,
  },
  quickUnreadBadge: {
    color: '#7a181d',
    fontFamily: 'Manrope_700Bold',
    fontSize: 11,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#dfb0b2',
    backgroundColor: '#fff1f2',
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  quickNewsUnreadCard: {
    borderColor: '#a7c592',
    backgroundColor: '#f3fde9',
  },
  quickNewsRowHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 8,
  },
  newsReadConfirmButtonDone: {
    borderColor: '#9fc9a1',
    backgroundColor: '#eff9f0',
  },
  newsTrackingActiveButton: {
    borderColor: '#8db271',
    backgroundColor: '#eef9e7',
  },
  newsTrackingCard: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#c7dfb8',
    backgroundColor: '#eef9e7',
    padding: 10,
    gap: 8,
  },
  newsTrackingRestaurantGroup: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#d5e8c9',
    backgroundColor: '#f7fff2',
    padding: 8,
    gap: 4,
  },
  quickNewsLink: {
    color: '#7f1b21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
    textDecorationLine: 'underline',
  },
  whatsNewPublishButton: {
    alignItems: 'center',
    borderRadius: 14,
    paddingVertical: 12,
    backgroundColor: '#ab1e24',
    borderWidth: 1,
    borderColor: '#97161c',
  },
  whatsNewPublishButtonText: {
    color: '#ffffff',
    fontFamily: 'Manrope_700Bold',
    fontSize: 14,
  },
  whatsNewAttachmentCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#de9ca0',
    backgroundColor: '#fff1f2',
    padding: 10,
    gap: 6,
  },
  restaurantFilterBlock: {
    gap: 6,
  },
  restaurantFilterSelectWrap: {
    gap: 6,
  },
  restaurantFilterSelectTrigger: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#dfb0b2',
    backgroundColor: '#ffffff',
    paddingHorizontal: 10,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  restaurantFilterSelectText: {
    color: '#7a181d',
    fontFamily: 'Manrope_700Bold',
    fontSize: 13,
    flex: 1,
  },
  restaurantFilterSelectChevron: {
    color: '#ab1e24',
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
  },
  restaurantFilterSelectList: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#dfb0b2',
    backgroundColor: '#ffffff',
    overflow: 'hidden',
  },
  restaurantFilterSelectItem: {
    paddingHorizontal: 10,
    paddingVertical: 9,
    borderBottomWidth: 1,
    borderBottomColor: '#efd8d9',
  },
  restaurantFilterSelectItemLast: {
    borderBottomWidth: 0,
  },
  restaurantFilterSelectItemActive: {
    backgroundColor: '#f8e2e4',
  },
  restaurantFilterSelectItemText: {
    color: '#7f1b21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
  },
  restaurantFilterSelectItemTextActive: {
    color: '#7a181d',
  },
  chartSupplierBlock: {
    borderWidth: 1,
    borderColor: '#edd3d5',
    backgroundColor: '#fffdfd',
    borderRadius: 12,
    padding: 10,
    gap: 8,
  },
  chartSupplierTitle: {
    color: '#7f1b21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 13,
  },
  chartSupplierTabs: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 2,
  },
  chartSupplierChip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#dfb0b2',
    backgroundColor: '#fffafa',
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  chartSupplierChipActive: {
    borderColor: '#b75d62',
    backgroundColor: '#f8e2e4',
  },
  chartSupplierChipText: {
    color: '#8d5458',
    fontFamily: 'Manrope_700Bold',
    fontSize: 11,
  },
  chartSupplierChipTextActive: {
    color: '#7a181d',
  },
  chartRowHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  chartRowLabel: {
    color: '#8d5458',
    fontFamily: 'Manrope_700Bold',
    fontSize: 11,
    flex: 1,
  },
  chartRowValue: {
    color: '#7a181d',
    fontFamily: 'Manrope_700Bold',
    fontSize: 11,
  },
  chartTrack: {
    width: '100%',
    height: 8,
    borderRadius: 999,
    backgroundColor: '#f4dfe0',
    overflow: 'hidden',
  },
  chartBar: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: '#d86e73',
  },
  chartWrap: {
    minHeight: 306,
  },
  chartScrollContent: {
    paddingRight: 8,
  },
  lineChartCanvas: {
    height: 304,
    position: 'relative',
  },
  lineChartGridRow: {
    position: 'absolute',
    left: 0,
    right: 0,
    flexDirection: 'row',
    alignItems: 'center',
  },
  lineChartYLabel: {
    width: 30,
    textAlign: 'right',
    color: '#8d5458',
    fontFamily: 'Manrope_700Bold',
    fontSize: 10,
    marginRight: 4,
  },
  lineChartGridLine: {
    flex: 1,
    borderTopWidth: 1,
    borderTopColor: '#f0d7d9',
  },
  lineChartAxisY: {
    position: 'absolute',
    width: 1,
    backgroundColor: '#c88c90',
  },
  lineChartAxisX: {
    position: 'absolute',
    height: 1,
    backgroundColor: '#c88c90',
  },
  lineChartSegment: {
    position: 'absolute',
    height: 2,
    backgroundColor: '#ab1e24',
  },
  lineChartPoint: {
    position: 'absolute',
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#ab1e24',
    borderWidth: 1,
    borderColor: '#ffffff',
  },
  lineChartValue: {
    position: 'absolute',
    width: 36,
    textAlign: 'center',
    color: '#7f1b21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 10,
  },
  lineChartProductLabel: {
    position: 'absolute',
    width: 80,
    textAlign: 'center',
    color: '#7f1b21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 10,
    lineHeight: 12,
  },
  quickMetaInlineRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  quickInlineCell: {
    flex: 1,
  },
  quickMetaHeaderText: {
    color: '#8d5458',
    fontFamily: 'Manrope_700Bold',
    fontSize: 10,
    textTransform: 'uppercase',
  },
  quickMetaValueText: {
    color: '#7f1b21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
  },
  quickMetaInlineText: {
    color: '#8d5458',
    fontFamily: 'Manrope_700Bold',
    fontSize: 11,
    flex: 1,
  },
  quickEyeSpacer: {
    width: 34,
  },
  errorText: {
    color: '#b42318',
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
  },
  orderPreviewFrame: {
    width: '100%',
    height: 520,
    borderWidth: 1,
    borderColor: '#dfb0b2',
    borderRadius: 10,
    backgroundColor: '#ffffff',
  },
  previewModalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(41, 8, 10, 0.45)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 18,
  },
  previewModalCard: {
    width: '96%',
    maxWidth: 980,
    backgroundColor: '#fff9f9',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#e2b9bb',
    padding: 14,
    gap: 12,
  },
  levelModalCard: {
    width: '94%',
    maxWidth: 620,
    maxHeight: '80%',
    backgroundColor: '#fff9f9',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#e2b9bb',
    padding: 14,
    gap: 12,
  },
  previewModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
  },
  title: {
    color: '#7a181d',
    fontFamily: 'Manrope_700Bold',
    fontSize: 24,
    lineHeight: 30,
  },
  subtitle: {
    color: '#8d5458',
    fontFamily: 'Manrope_400Regular',
    fontSize: 13,
  },
  pillRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  pill: {
    backgroundColor: '#f3dcdd',
    color: '#7f1b21',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
  },
  meta: {
    color: '#7d4a4f',
    fontFamily: 'Manrope_400Regular',
    fontSize: 14,
  },
  secondaryButton: {
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#d39a9d',
    borderRadius: 14,
    paddingVertical: 12,
    backgroundColor: '#fffafa',
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  secondaryButtonText: {
    color: '#7f1b21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 14,
  },
  eyePreviewButton: {
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#d39a9d',
    borderRadius: 17,
    backgroundColor: '#fffafa',
  },
  iconActionButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#d39a9d',
    backgroundColor: '#fffafa',
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconDeleteButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#d88084',
    backgroundColor: '#fff1f2',
    alignItems: 'center',
    justifyContent: 'center',
  },
  levelListWrap: {
    maxHeight: 460,
  },
  levelListContent: {
    gap: 8,
    paddingBottom: 8,
  },
  levelListItem: {
    borderWidth: 1,
    borderColor: '#dfb0b2',
    backgroundColor: '#fffafa',
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  levelListItemActive: {
    backgroundColor: '#f8e2e4',
    borderColor: '#d79ea1',
  },
  levelListItemText: {
    color: '#7f1b21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
    flexShrink: 1,
  },
  levelListItemTextActive: {
    color: '#7a181d',
  },
  dangerButton: {
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#d88084',
    borderRadius: 14,
    paddingVertical: 12,
    backgroundColor: '#fff1f2',
  },
  dangerButtonText: {
    color: '#ab1e24',
    fontFamily: 'Manrope_700Bold',
    fontSize: 14,
  },
});
