import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  card: {
    backgroundColor: 'rgba(255,255,255,0.92)',
    borderRadius: 22,
    padding: 18,
    borderWidth: 1,
    borderColor: '#e8c3c4',
    gap: 12,
  },
  stackCardWrap: {
    gap: 14,
  },
  managerDashboardLayout: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 14,
    flexWrap: 'wrap',
  },
  managerLeftCard: {
    flexBasis: 320,
    flexGrow: 1,
    minWidth: 280,
  },
  quickColumn: {
    flexBasis: 420,
    flexGrow: 1,
    minWidth: 300,
    gap: 12,
  },
  quickBlock: {
    backgroundColor: 'rgba(255,255,255,0.92)',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#e8c3c4',
    padding: 14,
    gap: 10,
  },
  quickBlockTitle: {
    color: '#7f1b21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 15,
  },
  quickSearchInput: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#dfb0b2',
    backgroundColor: '#ffffff',
    color: '#7a181d',
    fontFamily: 'Manrope_400Regular',
    fontSize: 13,
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  quickRowCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#efd8d9',
    backgroundColor: '#fff9f9',
    padding: 10,
    gap: 6,
  },
  quickRowTitle: {
    color: '#7f1b21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 13,
  },
  errorText: {
    color: '#b42318',
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
  },
  orderPreviewFrame: {
    width: '100%',
    height: 520,
    borderWidth: 1,
    borderColor: '#dfb0b2',
    borderRadius: 10,
    backgroundColor: '#ffffff',
  },
  previewModalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(41, 8, 10, 0.45)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 18,
  },
  previewModalCard: {
    width: '96%',
    maxWidth: 980,
    backgroundColor: '#fff9f9',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#e2b9bb',
    padding: 14,
    gap: 12,
  },
  previewModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
  },
  title: {
    color: '#7a181d',
    fontFamily: 'Manrope_700Bold',
    fontSize: 24,
    lineHeight: 30,
  },
  subtitle: {
    color: '#8d5458',
    fontFamily: 'Manrope_400Regular',
    fontSize: 13,
  },
  pillRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  pill: {
    backgroundColor: '#f3dcdd',
    color: '#7f1b21',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    fontFamily: 'Manrope_700Bold',
    fontSize: 12,
  },
  meta: {
    color: '#7d4a4f',
    fontFamily: 'Manrope_400Regular',
    fontSize: 14,
  },
  secondaryButton: {
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#d39a9d',
    borderRadius: 14,
    paddingVertical: 12,
    backgroundColor: '#fffafa',
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  secondaryButtonText: {
    color: '#7f1b21',
    fontFamily: 'Manrope_700Bold',
    fontSize: 14,
  },
  dangerButton: {
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#d88084',
    borderRadius: 14,
    paddingVertical: 12,
    backgroundColor: '#fff1f2',
  },
  dangerButtonText: {
    color: '#ab1e24',
    fontFamily: 'Manrope_700Bold',
    fontSize: 14,
  },
});
